-- Seed profiles, batch 11 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-028@genuinesugarmummies.com', 'Esther Nambooze', '/seed/sugarmums/photo_34_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_34_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, clean communication, discreet. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, clean communication, discreet. Preferred age range: 21-34.', 45, 'Jinja', 'Uganda', 'Jinja', '+256723183958', '+256723183958', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, clean communication, discreet, honest', '21-34', ARRAY['art galleries', 'fashion', 'dancing', 'coffee dates']::TEXT[], ARRAY['mentorship', 'private dates', 'long-term arrangement', 'respectful companionship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 5494, 347, true, 'silver', true, '2026-06-25T09:08:59+00', '2026-06-25T09:08:59+00', '2026-05-28T08:24:59+00'),
('seed+sugar_mummy-029@genuinesugarmummies.com', 'Fridah Nkurunziza', '/seed/sugarmums/photo_34_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_34_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, consistent, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, consistent, kind. Preferred age range: 21-34.', 46, 'Arusha', 'Tanzania', 'Arusha', '+255791929924', '+255791929924', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, consistent, kind, clean communication', '21-34', ARRAY['art galleries', 'business events', 'photography', 'beach walks']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'premium experiences', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 694, 70, true, 'silver', true, '2026-06-25T09:01:59+00', '2026-06-25T09:01:59+00', '2026-05-27T07:24:59+00'),
('seed+sugar_mummy-030@genuinesugarmummies.com', 'Gladys Okello', '/seed/sugarmums/photo_35_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_35_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, well groomed, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, well groomed, respectful. Preferred age range: 21-34.', 47, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250718347459', '+250718347459', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'serious about meeting, well groomed, respectful, generous', '21-34', ARRAY['coffee dates', 'dancing', 'photography', 'spa days']::TEXT[], ARRAY['meaningful conversations', 'respectful companionship', 'serious matches', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 5365, 809, true, 'silver', true, '2026-06-25T08:54:59+00', '2026-06-25T08:54:59+00', '2026-05-26T06:24:59+00'),
('seed+sugar_mummy-031@genuinesugarmummies.com', 'Harriet Chebet', '/seed/sugarmums/photo_35_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_35_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, generous, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, generous, clean communication. Preferred age range: 21-34.', 48, 'Thika', 'Kenya', 'Thika', '+254756517368', '+254756517368', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, generous, clean communication, discreet', '21-34', ARRAY['beach walks', 'business events', 'fine dining', 'cooking']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'premium experiences', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5401, 333, true, 'silver', true, '2026-06-25T08:47:59+00', '2026-06-25T08:47:59+00', '2026-05-25T05:24:59+00'),
('seed+sugar_mummy-032@genuinesugarmummies.com', 'Irene Johnson', '/seed/sugarmums/photo_36_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_36_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, discreet, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, discreet, honest. Preferred age range: 21-34.', 49, 'Nakuru', 'Kenya', 'Nakuru', '+254767324993', '+254767324993', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, discreet, honest, consistent', '21-34', ARRAY['travel', 'fine dining', 'photography', 'weekend drives']::TEXT[], ARRAY['discreet connection', 'verified members', 'long-term arrangement', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2419, 638, true, 'silver', true, '2026-06-25T08:40:59+00', '2026-06-25T08:40:59+00', '2026-05-24T04:24:59+00'),
('seed+sugar_mummy-033@genuinesugarmummies.com', 'Josephine Taylor', '/seed/sugarmums/photo_37_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_37_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, serious about meeting, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, serious about meeting, generous. Preferred age range: 21-34.', 50, 'Nakuru', 'Kenya', 'Nakuru', '+254779404466', '+254779404466', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, serious about meeting, generous, discreet', '21-34', ARRAY['travel', 'weekend drives', 'wine tasting', 'art galleries']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'private dates', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 7054, 319, true, 'silver', true, '2026-06-25T08:33:59+00', '2026-06-25T08:33:59+00', '2026-05-23T03:24:59+00'),
('seed+sugar_mummy-034@genuinesugarmummies.com', 'Lydia Wanjiku', '/seed/sugarmums/photo_38_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_38_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, respectful, consistent. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, respectful, consistent. Preferred age range: 21-34.', 51, 'Kisumu', 'Kenya', 'Kisumu', '+254783486831', '+254783486831', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, respectful, consistent, discreet', '21-34', ARRAY['dancing', 'fashion', 'coffee dates', 'live music']::TEXT[], ARRAY['private dates', 'lifestyle support', 'meaningful conversations', 'serious matches']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 6663, 490, true, 'silver', true, '2026-06-25T08:26:59+00', '2026-06-25T08:26:59+00', '2026-05-22T02:24:59+00'),
('seed+sugar_mummy-035@genuinesugarmummies.com', 'Martha Achieng', '/seed/sugarmums/photo_3_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_3_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, generous, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, generous, clean communication. Preferred age range: 21-34.', 52, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254792177767', '+254792177767', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, generous, clean communication, well groomed', '21-34', ARRAY['wine tasting', 'travel', 'cooking', 'fitness']::TEXT[], ARRAY['long-term arrangement', 'discreet connection', 'serious matches', 'verified members']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3896, 472, true, 'silver', true, '2026-06-25T08:19:59+00', '2026-06-25T08:19:59+00', '2026-05-21T01:24:59+00'),
('seed+sugar_mummy-036@genuinesugarmummies.com', 'Naomi Nabwire', '/seed/sugarmums/photo_3_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugarmums/photo_3_2026-06-25_14-22-09.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, respectful, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, respectful, generous. Preferred age range: 21-34.', 53, 'Kisumu', 'Kenya', 'Kisumu', '+254729418897', '+254729418897', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, respectful, generous, discreet', '21-34', ARRAY['wine tasting', 'cooking', 'dancing', 'coffee dates']::TEXT[], ARRAY['serious matches', 'meaningful conversations', 'verified members', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1406, 180, true, 'silver', true, '2026-06-25T08:12:59+00', '2026-06-25T08:12:59+00', '2026-05-20T00:24:59+00'),
('seed+sugar_mummy-037@genuinesugarmummies.com', 'Priscilla Mugisha', '/seed/sugarmums/photo_41_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_41_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, honest, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, honest, generous. Preferred age range: 21-34.', 54, 'Nakuru', 'Kenya', 'Nakuru', '+254792276827', '+254792276827', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, honest, generous, serious about meeting', '21-34', ARRAY['fashion', 'coffee dates', 'fitness', 'travel']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'serious matches', 'private dates']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4836, 618, true, 'silver', true, '2026-06-25T08:05:59+00', '2026-06-25T08:05:59+00', '2026-05-18T23:24:59+00'),
('seed+sugar_mummy-038@genuinesugarmummies.com', 'Sarah Hassan', '/seed/sugarmums/photo_42_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_42_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, discreet, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, discreet, emotionally mature. Preferred age range: 21-34.', 55, 'Kampala', 'Uganda', 'Kampala', '+256783536822', '+256783536822', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, discreet, emotionally mature, kind', '21-34', ARRAY['spa days', 'business events', 'photography', 'cooking']::TEXT[], ARRAY['premium experiences', 'respectful companionship', 'verified members', 'discreet connection']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 5314, 644, true, 'silver', true, '2026-06-25T07:58:59+00', '2026-06-25T07:58:59+00', '2026-05-17T22:24:59+00'),
('seed+sugar_mummy-039@genuinesugarmummies.com', 'Tabitha Wafula', '/seed/sugarmums/photo_43_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_43_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, discreet, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, discreet, well groomed. Preferred age range: 21-34.', 56, 'Arusha', 'Tanzania', 'Arusha', '+255798162823', '+255798162823', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, discreet, well groomed, respectful', '21-34', ARRAY['wine tasting', 'spa days', 'coffee dates', 'fitness']::TEXT[], ARRAY['mentorship', 'discreet connection', 'lifestyle support', 'long-term arrangement']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 3681, 173, true, 'silver', true, '2026-06-25T07:51:59+00', '2026-06-25T07:51:59+00', '2026-05-16T21:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
