-- Seed profiles, batch 2 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+mistress-013@genuinesugarmummies.com', 'Miriam Hassan', '/seed/mistresses/photo_21_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_21_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, well groomed, honest. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, well groomed, honest. Preferred age range: 38-68.', 25, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254741335612', '+254741335612', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'consistent, well groomed, honest, respectful', '38-68', ARRAY['cooking', 'business events', 'beach walks', 'live music']::TEXT[], ARRAY['verified members', 'lifestyle support', 'mentorship', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 2849, 77, true, 'silver', true, '2026-06-25T10:53:59+00', '2026-06-25T10:53:59+00', '2026-06-11T23:24:59+00'),
('seed+mistress-014@genuinesugarmummies.com', 'Nadia Wafula', '/seed/mistresses/photo_22_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_22_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, emotionally mature, generous. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, emotionally mature, generous. Preferred age range: 38-68.', 26, 'Nairobi', 'Kenya', 'Nairobi', '+254752174299', '+254752174299', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'respectful, emotionally mature, generous, serious about meeting', '38-68', ARRAY['business events', 'coffee dates', 'live music', 'wine tasting']::TEXT[], ARRAY['lifestyle support', 'respectful companionship', 'private dates', 'premium experiences']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 2029, 538, true, 'silver', true, '2026-06-25T10:46:59+00', '2026-06-25T10:46:59+00', '2026-06-10T22:24:59+00'),
('seed+mistress-015@genuinesugarmummies.com', 'Olivia Smith', '/seed/mistresses/photo_23_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_23_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, kind, emotionally mature. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, kind, emotionally mature. Preferred age range: 38-68.', 27, 'Eldoret', 'Kenya', 'Eldoret', '+254722790993', '+254722790993', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'well groomed, kind, emotionally mature, respectful', '38-68', ARRAY['spa days', 'art galleries', 'live music', 'coffee dates']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'lifestyle support', 'long-term arrangement']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 2982, 453, true, 'silver', true, '2026-06-25T10:39:59+00', '2026-06-25T10:39:59+00', '2026-06-09T21:24:59+00'),
('seed+mistress-016@genuinesugarmummies.com', 'Patricia Brown', '/seed/mistresses/photo_24_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_24_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, generous, emotionally mature. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, generous, emotionally mature. Preferred age range: 38-68.', 28, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254734662336', '+254734662336', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'consistent, generous, emotionally mature, honest', '38-68', ARRAY['beach walks', 'art galleries', 'photography', 'fine dining']::TEXT[], ARRAY['private dates', 'respectful companionship', 'long-term arrangement', 'premium experiences']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 1228, 471, true, 'silver', true, '2026-06-25T10:32:59+00', '2026-06-25T10:32:59+00', '2026-06-08T20:24:59+00'),
('seed+mistress-017@genuinesugarmummies.com', 'Queen Otieno', '/seed/mistresses/photo_25_2026-06-24_14-00-45.jpg', ARRAY['/seed/mistresses/photo_25_2026-06-24_14-00-45.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, respectful, generous. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, respectful, generous. Preferred age range: 38-68.', 29, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254740274389', '+254740274389', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'honest, respectful, generous, kind', '38-68', ARRAY['weekend drives', 'fitness', 'art galleries', 'live music']::TEXT[], ARRAY['private dates', 'discreet connection', 'serious matches', 'respectful companionship']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4058, 428, true, 'silver', true, '2026-06-25T10:25:59+00', '2026-06-25T10:25:59+00', '2026-06-07T19:24:59+00'),
('seed+mistress-018@genuinesugarmummies.com', 'Ruth Njeri', '/seed/mistresses/photo_25_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_25_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, well groomed, serious about meeting. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, well groomed, serious about meeting. Preferred age range: 38-68.', 21, 'Entebbe', 'Uganda', 'Entebbe', '+256799865990', '+256799865990', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'discreet, well groomed, serious about meeting, emotionally mature', '38-68', ARRAY['live music', 'cooking', 'beach walks', 'fine dining']::TEXT[], ARRAY['meaningful conversations', 'long-term arrangement', 'respectful companionship', 'lifestyle support']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4632, 814, true, 'silver', true, '2026-06-25T10:18:59+00', '2026-06-25T10:18:59+00', '2026-06-06T18:24:59+00'),
('seed+mistress-019@genuinesugarmummies.com', 'Stella Mutiso', '/seed/mistresses/photo_26_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_26_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, respectful, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, respectful, consistent. Preferred age range: 38-68.', 22, 'Mwanza', 'Tanzania', 'Mwanza', '+255716712554', '+255716712554', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'honest, respectful, consistent, serious about meeting', '38-68', ARRAY['photography', 'art galleries', 'weekend drives', 'live music']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'respectful companionship', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4199, 500, true, 'silver', true, '2026-06-25T10:11:59+00', '2026-06-25T10:11:59+00', '2026-06-05T17:24:59+00'),
('seed+mistress-020@genuinesugarmummies.com', 'Talia Kato', '/seed/mistresses/photo_27_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_27_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, serious matches. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, emotionally mature, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, serious matches. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, emotionally mature, respectful. Preferred age range: 38-68.', 23, 'Kigali', 'Rwanda', 'Kigali', '+250720539589', '+250720539589', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'generous, emotionally mature, respectful, discreet', '38-68', ARRAY['fine dining', 'coffee dates', 'travel', 'weekend drives']::TEXT[], ARRAY['private dates', 'serious matches', 'lifestyle support', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4861, 685, true, 'silver', true, '2026-06-25T10:04:59+00', '2026-06-25T10:04:59+00', '2026-06-04T16:24:59+00'),
('seed+mistress-021@genuinesugarmummies.com', 'Uma Mutesi', '/seed/mistresses/photo_28_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_28_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 38-68.', 24, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254719109767', '+254719109767', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, discreet, well groomed, serious about meeting', '38-68', ARRAY['coffee dates', 'fashion', 'fitness', 'live music']::TEXT[], ARRAY['premium experiences', 'lifestyle support', 'mentorship', 'verified members']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5168, 481, true, 'silver', true, '2026-06-25T09:57:59+00', '2026-06-25T09:57:59+00', '2026-06-03T15:24:59+00'),
('seed+mistress-022@genuinesugarmummies.com', 'Vanessa Kimani', '/seed/mistresses/photo_29_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_29_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, emotionally mature, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, emotionally mature, consistent. Preferred age range: 38-68.', 25, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254730559469', '+254730559469', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'generous, emotionally mature, consistent, clean communication', '38-68', ARRAY['travel', 'wine tasting', 'coffee dates', 'live music']::TEXT[], ARRAY['verified members', 'mentorship', 'meaningful conversations', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4530, 865, true, 'silver', true, '2026-06-25T09:50:59+00', '2026-06-25T09:50:59+00', '2026-06-02T14:24:59+00'),
('seed+mistress-023@genuinesugarmummies.com', 'Winnie Maina', '/seed/mistresses/photo_30_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_30_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: respectful companionship, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, clean communication, discreet. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: respectful companionship, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, clean communication, discreet. Preferred age range: 38-68.', 26, 'Eldoret', 'Kenya', 'Eldoret', '+254723878480', '+254723878480', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'generous, clean communication, discreet, respectful', '38-68', ARRAY['business events', 'dancing', 'spa days', 'coffee dates']::TEXT[], ARRAY['respectful companionship', 'verified members', 'mentorship', 'premium experiences']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 1353, 578, true, 'silver', true, '2026-06-25T09:43:59+00', '2026-06-25T09:43:59+00', '2026-06-01T13:24:59+00'),
('seed+mistress-024@genuinesugarmummies.com', 'Yvonne Williams', '/seed/mistresses/photo_36_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_36_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, discreet, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, discreet, respectful. Preferred age range: 38-68.', 27, 'Eldoret', 'Kenya', 'Eldoret', '+254791544151', '+254791544151', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'well groomed, discreet, respectful, serious about meeting', '38-68', ARRAY['fitness', 'business events', 'live music', 'photography']::TEXT[], ARRAY['premium experiences', 'lifestyle support', 'mentorship', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 2346, 861, true, 'silver', true, '2026-06-25T09:36:59+00', '2026-06-25T09:36:59+00', '2026-06-01T12:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
