-- Seed profiles, batch 7 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_daddy-025@genuinesugarmummies.com', 'Kevin Mwangi', '/seed/sugar-dads/photo_45_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_45_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, emotionally mature, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, emotionally mature, well groomed. Preferred age range: 21-35.', 43, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254728343467', '+254728343467', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'kind, emotionally mature, well groomed, discreet', '21-35', ARRAY['business events', 'spa days', 'dancing', 'weekend drives']::TEXT[], ARRAY['meaningful conversations', 'serious matches', 'private dates', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5305, 484, true, 'silver', true, '2026-06-25T09:29:59+00', '2026-06-25T09:29:59+00', '2026-05-31T11:24:59+00'),
('seed+sugar_daddy-026@genuinesugarmummies.com', 'Francis Kamau', '/seed/sugar-dads/photo_46_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_46_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, consistent, discreet. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, consistent, discreet. Preferred age range: 21-35.', 44, 'Eldoret', 'Kenya', 'Eldoret', '+254764823846', '+254764823846', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, consistent, discreet, honest', '21-35', ARRAY['art galleries', 'fitness', 'spa days', 'fine dining']::TEXT[], ARRAY['discreet connection', 'mentorship', 'meaningful conversations', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3822, 268, true, 'silver', true, '2026-06-25T09:22:59+00', '2026-06-25T09:22:59+00', '2026-05-30T10:24:59+00'),
('seed+sugar_daddy-027@genuinesugarmummies.com', 'Kenneth Kariuki', '/seed/sugar-dads/photo_47_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_47_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: lifestyle support, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, serious about meeting, respectful. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: lifestyle support, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, serious about meeting, respectful. Preferred age range: 21-35.', 45, 'Eldoret', 'Kenya', 'Eldoret', '+254794515032', '+254794515032', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, serious about meeting, respectful, kind', '21-35', ARRAY['live music', 'beach walks', 'art galleries', 'travel']::TEXT[], ARRAY['lifestyle support', 'long-term arrangement', 'premium experiences', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 146, 293, true, 'silver', true, '2026-06-25T09:15:59+00', '2026-06-25T09:15:59+00', '2026-05-29T09:24:59+00'),
('seed+sugar_daddy-028@genuinesugarmummies.com', 'Collins Nambooze', '/seed/sugar-dads/photo_48_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_48_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, consistent, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, consistent, serious about meeting. Preferred age range: 21-35.', 46, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254734751051', '+254734751051', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'emotionally mature, consistent, serious about meeting, honest', '21-35', ARRAY['cooking', 'spa days', 'dancing', 'photography']::TEXT[], ARRAY['respectful companionship', 'discreet connection', 'mentorship', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5632, 268, true, 'silver', true, '2026-06-25T09:08:59+00', '2026-06-25T09:08:59+00', '2026-05-28T08:24:59+00'),
('seed+sugar_daddy-029@genuinesugarmummies.com', 'Allan Nkurunziza', '/seed/sugar-dads/photo_49_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_49_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, consistent, clean communication. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, consistent, clean communication. Preferred age range: 21-35.', 47, 'Kisumu', 'Kenya', 'Kisumu', '+254747442589', '+254747442589', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'serious about meeting, consistent, clean communication, respectful', '21-35', ARRAY['spa days', 'travel', 'wine tasting', 'dancing']::TEXT[], ARRAY['respectful companionship', 'mentorship', 'discreet connection', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3483, 777, true, 'silver', true, '2026-06-25T09:01:59+00', '2026-06-25T09:01:59+00', '2026-05-27T07:24:59+00'),
('seed+sugar_daddy-030@genuinesugarmummies.com', 'Eric Okello', '/seed/sugar-dads/photo_50_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_50_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 21-35.', 48, 'Kisumu', 'Kenya', 'Kisumu', '+254747882824', '+254747882824', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'clean communication, discreet, well groomed, kind', '21-35', ARRAY['live music', 'weekend drives', 'dancing', 'coffee dates']::TEXT[], ARRAY['premium experiences', 'verified members', 'mentorship', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2854, 903, true, 'silver', true, '2026-06-25T08:54:59+00', '2026-06-25T08:54:59+00', '2026-05-26T06:24:59+00'),
('seed+sugar_daddy-031@genuinesugarmummies.com', 'Mark Chebet', '/seed/sugar-dads/photo_51_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_51_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, respectful, discreet. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, respectful, discreet. Preferred age range: 21-35.', 49, 'Kampala', 'Uganda', 'Kampala', '+256725576877', '+256725576877', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'kind, respectful, discreet, well groomed', '21-35', ARRAY['art galleries', 'travel', 'weekend drives', 'live music']::TEXT[], ARRAY['long-term arrangement', 'verified members', 'premium experiences', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5591, 389, true, 'silver', true, '2026-06-25T08:47:59+00', '2026-06-25T08:47:59+00', '2026-05-25T05:24:59+00'),
('seed+sugar_daddy-032@genuinesugarmummies.com', 'Philip Johnson', '/seed/sugar-dads/photo_52_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_52_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, honest, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, honest, consistent. Preferred age range: 21-35.', 50, 'Mwanza', 'Tanzania', 'Mwanza', '+255738779112', '+255738779112', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, honest, consistent, discreet', '21-35', ARRAY['spa days', 'fitness', 'business events', 'beach walks']::TEXT[], ARRAY['premium experiences', 'private dates', 'lifestyle support', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5285, 76, true, 'silver', true, '2026-06-25T08:40:59+00', '2026-06-25T08:40:59+00', '2026-05-24T04:24:59+00'),
('seed+sugar_daddy-033@genuinesugarmummies.com', 'Dennis Taylor', '/seed/sugar-dads/photo_53_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_53_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, well groomed. Preferred age range: 21-35.', 51, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250722346205', '+250722346205', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, discreet, well groomed, serious about meeting', '21-35', ARRAY['wine tasting', 'photography', 'fitness', 'spa days']::TEXT[], ARRAY['long-term arrangement', 'private dates', 'meaningful conversations', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4483, 920, true, 'silver', true, '2026-06-25T08:33:59+00', '2026-06-25T08:33:59+00', '2026-05-23T03:24:59+00'),
('seed+sugar_daddy-034@genuinesugarmummies.com', 'Oscar Wanjiku', '/seed/sugar-dads/photo_54_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_54_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, well groomed, kind. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, well groomed, kind. Preferred age range: 21-35.', 52, 'Kisumu', 'Kenya', 'Kisumu', '+254714823811', '+254714823811', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'generous, well groomed, kind, clean communication', '21-35', ARRAY['beach walks', 'art galleries', 'fashion', 'spa days']::TEXT[], ARRAY['verified members', 'long-term arrangement', 'meaningful conversations', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1859, 391, true, 'silver', true, '2026-06-25T08:26:59+00', '2026-06-25T08:26:59+00', '2026-05-22T02:24:59+00'),
('seed+sugar_daddy-035@genuinesugarmummies.com', 'Alex Achieng', '/seed/sugar-dads/photo_55_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_55_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, discreet, emotionally mature. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, discreet, emotionally mature. Preferred age range: 21-35.', 53, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254768196126', '+254768196126', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'kind, discreet, emotionally mature, respectful', '21-35', ARRAY['art galleries', 'live music', 'fashion', 'travel']::TEXT[], ARRAY['premium experiences', 'verified members', 'serious matches', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1817, 690, true, 'silver', true, '2026-06-25T08:19:59+00', '2026-06-25T08:19:59+00', '2026-05-21T01:24:59+00'),
('seed+sugar_daddy-036@genuinesugarmummies.com', 'Lawrence Nabwire', '/seed/sugar-dads/photo_56_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_56_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: lifestyle support, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, emotionally mature, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: lifestyle support, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, emotionally mature, serious about meeting. Preferred age range: 21-35.', 54, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254739444519', '+254739444519', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'honest, emotionally mature, serious about meeting, kind', '21-35', ARRAY['fine dining', 'wine tasting', 'dancing', 'fashion']::TEXT[], ARRAY['lifestyle support', 'meaningful conversations', 'serious matches', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1288, 804, true, 'silver', true, '2026-06-25T08:12:59+00', '2026-06-25T08:12:59+00', '2026-05-20T00:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
