-- Seed profiles, batch 6 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_daddy-013@genuinesugarmummies.com', 'Victor Hassan', '/seed/sugar-dads/photo_23_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_23_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, discreet, clean communication. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, discreet, clean communication. Preferred age range: 21-35.', 55, 'Kigali', 'Rwanda', 'Kigali', '+250765765620', '+250765765620', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, discreet, clean communication, honest', '21-35', ARRAY['dancing', 'spa days', 'fitness', 'business events']::TEXT[], ARRAY['respectful companionship', 'meaningful conversations', 'discreet connection', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4108, 845, true, 'silver', true, '2026-06-25T10:53:59+00', '2026-06-25T10:53:59+00', '2026-06-11T23:24:59+00'),
('seed+sugar_daddy-014@genuinesugarmummies.com', 'Samuel Wafula', '/seed/sugar-dads/photo_24_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_24_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, well groomed, discreet. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, well groomed, discreet. Preferred age range: 21-35.', 56, 'Mombasa', 'Kenya', 'Mombasa', '+254761953085', '+254761953085', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'kind, well groomed, discreet, consistent', '21-35', ARRAY['art galleries', 'fashion', 'beach walks', 'cooking']::TEXT[], ARRAY['premium experiences', 'private dates', 'meaningful conversations', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4586, 790, true, 'silver', true, '2026-06-25T10:46:59+00', '2026-06-25T10:46:59+00', '2026-06-10T22:24:59+00'),
('seed+sugar_daddy-015@genuinesugarmummies.com', 'Patrick Smith', '/seed/sugar-dads/photo_25_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_25_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, respectful, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, respectful, well groomed. Preferred age range: 21-35.', 57, 'Nairobi', 'Kenya', 'Nairobi', '+254716296694', '+254716296694', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'honest, respectful, well groomed, emotionally mature', '21-35', ARRAY['art galleries', 'travel', 'fashion', 'fitness']::TEXT[], ARRAY['premium experiences', 'private dates', 'long-term arrangement', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3043, 542, true, 'silver', true, '2026-06-25T10:39:59+00', '2026-06-25T10:39:59+00', '2026-06-09T21:24:59+00'),
('seed+sugar_daddy-016@genuinesugarmummies.com', 'Joseph Brown', '/seed/sugar-dads/photo_26_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_26_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, discreet, well groomed. Preferred age range: 21-35.', 58, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254772227324', '+254772227324', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'clean communication, discreet, well groomed, consistent', '21-35', ARRAY['dancing', 'art galleries', 'spa days', 'cooking']::TEXT[], ARRAY['respectful companionship', 'lifestyle support', 'mentorship', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5241, 41, true, 'silver', true, '2026-06-25T10:32:59+00', '2026-06-25T10:32:59+00', '2026-06-08T20:24:59+00'),
('seed+sugar_daddy-017@genuinesugarmummies.com', 'Brian Otieno', '/seed/sugar-dads/photo_27_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_27_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, generous, emotionally mature. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: kind, generous, emotionally mature. Preferred age range: 21-35.', 59, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254724583863', '+254724583863', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'kind, generous, emotionally mature, serious about meeting', '21-35', ARRAY['dancing', 'live music', 'photography', 'weekend drives']::TEXT[], ARRAY['mentorship', 'verified members', 'respectful companionship', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5386, 132, true, 'silver', true, '2026-06-25T10:25:59+00', '2026-06-25T10:25:59+00', '2026-06-07T19:24:59+00'),
('seed+sugar_daddy-018@genuinesugarmummies.com', 'Martin Njeri', '/seed/sugar-dads/photo_28_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_28_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, well groomed, clean communication. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, well groomed, clean communication. Preferred age range: 21-35.', 60, 'Kisumu', 'Kenya', 'Kisumu', '+254734728492', '+254734728492', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'emotionally mature, well groomed, clean communication, serious about meeting', '21-35', ARRAY['art galleries', 'photography', 'fitness', 'coffee dates']::TEXT[], ARRAY['mentorship', 'long-term arrangement', 'discreet connection', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6193, 532, true, 'silver', true, '2026-06-25T10:18:59+00', '2026-06-25T10:18:59+00', '2026-06-06T18:24:59+00'),
('seed+sugar_daddy-019@genuinesugarmummies.com', 'Stephen Mutiso', '/seed/sugar-dads/photo_39_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_39_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, honest. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, honest. Preferred age range: 21-35.', 61, 'Kisumu', 'Kenya', 'Kisumu', '+254785708093', '+254785708093', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, discreet, honest, kind', '21-35', ARRAY['cooking', 'travel', 'fitness', 'beach walks']::TEXT[], ARRAY['premium experiences', 'verified members', 'mentorship', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4091, 687, true, 'silver', true, '2026-06-25T10:11:59+00', '2026-06-25T10:11:59+00', '2026-06-05T17:24:59+00'),
('seed+sugar_daddy-020@genuinesugarmummies.com', 'Peter Kato', '/seed/sugar-dads/photo_40_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_40_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: consistent, emotionally mature, honest. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: consistent, emotionally mature, honest. Preferred age range: 21-35.', 62, 'Kisumu', 'Kenya', 'Kisumu', '+254759344907', '+254759344907', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'consistent, emotionally mature, honest, discreet', '21-35', ARRAY['art galleries', 'coffee dates', 'wine tasting', 'fashion']::TEXT[], ARRAY['premium experiences', 'verified members', 'long-term arrangement', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6433, 888, true, 'silver', true, '2026-06-25T10:04:59+00', '2026-06-25T10:04:59+00', '2026-06-04T16:24:59+00'),
('seed+sugar_daddy-021@genuinesugarmummies.com', 'Andrew Mutesi', '/seed/sugar-dads/photo_41_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_41_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, clean communication, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, clean communication, consistent. Preferred age range: 21-35.', 63, 'Entebbe', 'Uganda', 'Entebbe', '+256722986088', '+256722986088', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, clean communication, consistent, kind', '21-35', ARRAY['fine dining', 'fashion', 'photography', 'art galleries']::TEXT[], ARRAY['long-term arrangement', 'serious matches', 'meaningful conversations', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 896, 462, true, 'silver', true, '2026-06-25T09:57:59+00', '2026-06-25T09:57:59+00', '2026-06-03T15:24:59+00'),
('seed+sugar_daddy-022@genuinesugarmummies.com', 'Nicholas Kimani', '/seed/sugar-dads/photo_42_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_42_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, discreet, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, discreet, consistent. Preferred age range: 21-35.', 64, 'Mwanza', 'Tanzania', 'Mwanza', '+255798516791', '+255798516791', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, discreet, consistent, honest', '21-35', ARRAY['wine tasting', 'art galleries', 'fine dining', 'photography']::TEXT[], ARRAY['meaningful conversations', 'long-term arrangement', 'serious matches', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 737, 677, true, 'silver', true, '2026-06-25T09:50:59+00', '2026-06-25T09:50:59+00', '2026-06-02T14:24:59+00'),
('seed+sugar_daddy-023@genuinesugarmummies.com', 'Thomas Maina', '/seed/sugar-dads/photo_43_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_43_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, emotionally mature, discreet. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, emotionally mature, discreet. Preferred age range: 21-35.', 65, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250721555052', '+250721555052', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'generous, emotionally mature, discreet, serious about meeting', '21-35', ARRAY['cooking', 'spa days', 'coffee dates', 'beach walks']::TEXT[], ARRAY['premium experiences', 'discreet connection', 'respectful companionship', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6308, 112, true, 'silver', true, '2026-06-25T09:43:59+00', '2026-06-25T09:43:59+00', '2026-06-01T13:24:59+00'),
('seed+sugar_daddy-024@genuinesugarmummies.com', 'Simon Williams', '/seed/sugar-dads/photo_44_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_44_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, discreet, consistent. Preferred age range: 21-35.', 42, 'Mombasa', 'Kenya', 'Mombasa', '+254765252640', '+254765252640', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, discreet, consistent, clean communication', '21-35', ARRAY['art galleries', 'weekend drives', 'photography', 'fitness']::TEXT[], ARRAY['respectful companionship', 'serious matches', 'premium experiences', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4431, 262, true, 'silver', true, '2026-06-25T09:36:59+00', '2026-06-25T09:36:59+00', '2026-06-01T12:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
