-- Seed profiles, batch 14 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-064@genuinesugarmummies.com', 'Pauline Wafula', '/seed/sugarmums/photo_71_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_71_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, serious about meeting, discreet. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, serious about meeting, discreet. Preferred age range: 21-34.', 39, 'Thika', 'Kenya', 'Thika', '+254796854024', '+254796854024', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, serious about meeting, discreet, emotionally mature', '21-34', ARRAY['travel', 'weekend drives', 'coffee dates', 'beach walks']::TEXT[], ARRAY['verified members', 'meaningful conversations', 'lifestyle support', 'long-term arrangement']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3554, 569, true, 'silver', true, '2026-06-25T04:56:59+00', '2026-06-25T04:56:59+00', '2026-04-21T20:24:59+00'),
('seed+sugar_mummy-065@genuinesugarmummies.com', 'Regina Smith', '/seed/sugarmums/photo_72_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_72_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, respectful, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, respectful, emotionally mature. Preferred age range: 21-34.', 40, 'Nakuru', 'Kenya', 'Nakuru', '+254718205797', '+254718205797', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, respectful, emotionally mature, generous', '21-34', ARRAY['live music', 'art galleries', 'fashion', 'weekend drives']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'private dates', 'respectful companionship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 355, 620, true, 'silver', true, '2026-06-25T04:49:59+00', '2026-06-25T04:49:59+00', '2026-04-20T19:24:59+00'),
('seed+sugar_mummy-066@genuinesugarmummies.com', 'Sophia Brown', '/seed/sugarmums/photo_73_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_73_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, emotionally mature, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, emotionally mature, respectful. Preferred age range: 21-34.', 41, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254774403314', '+254774403314', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, emotionally mature, respectful, generous', '21-34', ARRAY['spa days', 'photography', 'fine dining', 'live music']::TEXT[], ARRAY['respectful companionship', 'long-term arrangement', 'discreet connection', 'private dates']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 6762, 251, true, 'silver', true, '2026-06-25T04:42:59+00', '2026-06-25T04:42:59+00', '2026-04-19T18:24:59+00'),
('seed+sugar_mummy-067@genuinesugarmummies.com', 'Anne Otieno', '/seed/sugarmums/photo_74_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_74_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, emotionally mature, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, emotionally mature, kind. Preferred age range: 21-34.', 42, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254745163918', '+254745163918', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, emotionally mature, kind, clean communication', '21-34', ARRAY['business events', 'dancing', 'spa days', 'fashion']::TEXT[], ARRAY['lifestyle support', 'mentorship', 'meaningful conversations', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4926, 582, true, 'silver', true, '2026-06-25T04:35:59+00', '2026-06-25T04:35:59+00', '2026-04-18T17:24:59+00'),
('seed+sugar_mummy-068@genuinesugarmummies.com', 'Christine Njeri', '/seed/sugarmums/photo_76_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_76_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, consistent, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, consistent, kind. Preferred age range: 21-34.', 43, 'Jinja', 'Uganda', 'Jinja', '+256729414455', '+256729414455', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, consistent, kind, emotionally mature', '21-34', ARRAY['spa days', 'beach walks', 'coffee dates', 'art galleries']::TEXT[], ARRAY['respectful companionship', 'premium experiences', 'long-term arrangement', 'discreet connection']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 1586, 397, true, 'silver', true, '2026-06-25T04:28:59+00', '2026-06-25T04:28:59+00', '2026-04-17T16:24:59+00'),
('seed+sugar_mummy-069@genuinesugarmummies.com', 'Doreen Mutiso', '/seed/sugarmums/photo_77_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_77_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, serious about meeting, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, serious about meeting, clean communication. Preferred age range: 21-34.', 44, 'Dar es Salaam', 'Tanzania', 'Dar es Salaam', '+255741367382', '+255741367382', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, serious about meeting, clean communication, emotionally mature', '21-34', ARRAY['cooking', 'live music', 'fitness', 'photography']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'respectful companionship', 'mentorship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 2785, 220, true, 'silver', true, '2026-06-25T04:21:59+00', '2026-06-25T04:21:59+00', '2026-04-16T15:24:59+00'),
('seed+sugar_mummy-070@genuinesugarmummies.com', 'Esther Kato', '/seed/sugarmums/photo_78_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_78_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, respectful, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, respectful, generous. Preferred age range: 21-34.', 45, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250785859489', '+250785859489', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'serious about meeting, respectful, generous, well groomed', '21-34', ARRAY['cooking', 'fashion', 'travel', 'coffee dates']::TEXT[], ARRAY['lifestyle support', 'respectful companionship', 'mentorship', 'serious matches']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 4658, 699, true, 'silver', true, '2026-06-25T04:14:59+00', '2026-06-25T04:14:59+00', '2026-04-15T14:24:59+00'),
('seed+sugar_mummy-071@genuinesugarmummies.com', 'Fridah Mutesi', '/seed/sugarmums/photo_79_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_79_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, well groomed, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, well groomed, emotionally mature. Preferred age range: 21-34.', 46, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254787837954', '+254787837954', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, well groomed, emotionally mature, consistent', '21-34', ARRAY['live music', 'cooking', 'fashion', 'fitness']::TEXT[], ARRAY['respectful companionship', 'lifestyle support', 'verified members', 'premium experiences']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3329, 221, true, 'silver', true, '2026-06-25T04:07:59+00', '2026-06-25T04:07:59+00', '2026-04-14T13:24:59+00'),
('seed+sugar_mummy-072@genuinesugarmummies.com', 'Gladys Kimani', '/seed/sugarmums/photo_80_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_80_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, consistent, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, consistent, well groomed. Preferred age range: 21-34.', 47, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254722941814', '+254722941814', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, consistent, well groomed, emotionally mature', '21-34', ARRAY['fashion', 'dancing', 'fitness', 'beach walks']::TEXT[], ARRAY['discreet connection', 'verified members', 'premium experiences', 'meaningful conversations']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3926, 751, true, 'silver', true, '2026-06-25T04:00:59+00', '2026-06-25T04:00:59+00', '2026-04-14T12:24:59+00'),
('seed+sugar_mummy-073@genuinesugarmummies.com', 'Harriet Maina', '/seed/sugarmums/photo_82_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_82_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, honest, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, honest, kind. Preferred age range: 21-34.', 48, 'Nakuru', 'Kenya', 'Nakuru', '+254729305721', '+254729305721', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, honest, kind, clean communication', '21-34', ARRAY['fashion', 'wine tasting', 'beach walks', 'fine dining']::TEXT[], ARRAY['serious matches', 'lifestyle support', 'meaningful conversations', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1964, 349, true, 'silver', true, '2026-06-25T03:53:59+00', '2026-06-25T03:53:59+00', '2026-04-13T11:24:59+00'),
('seed+sugar_mummy-074@genuinesugarmummies.com', 'Irene Williams', '/seed/sugarmums/photo_83_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_83_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, serious about meeting, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, serious about meeting, clean communication. Preferred age range: 21-34.', 49, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254755277487', '+254755277487', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, serious about meeting, clean communication, consistent', '21-34', ARRAY['cooking', 'live music', 'art galleries', 'coffee dates']::TEXT[], ARRAY['premium experiences', 'mentorship', 'discreet connection', 'serious matches']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 5980, 155, true, 'silver', true, '2026-06-25T03:46:59+00', '2026-06-25T03:46:59+00', '2026-04-12T10:24:59+00'),
('seed+sugar_mummy-075@genuinesugarmummies.com', 'Josephine Mwangi', '/seed/sugarmums/photo_85_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_85_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, serious about meeting, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, serious about meeting, kind. Preferred age range: 21-34.', 50, 'Kisumu', 'Kenya', 'Kisumu', '+254790342675', '+254790342675', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, serious about meeting, kind, generous', '21-34', ARRAY['wine tasting', 'coffee dates', 'spa days', 'fine dining']::TEXT[], ARRAY['verified members', 'respectful companionship', 'private dates', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 5873, 81, true, 'silver', true, '2026-06-25T03:39:59+00', '2026-06-25T03:39:59+00', '2026-04-11T09:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
