-- Seed profiles, batch 9 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-004@genuinesugarmummies.com', 'Rosemary Nkurunziza', '/seed/sugarmums/photo_12_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_12_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, well groomed, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, well groomed, kind. Preferred age range: 21-34.', 42, 'Nakuru', 'Kenya', 'Nakuru', '+254726498676', '+254726498676', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, well groomed, kind, generous', '21-34', ARRAY['fitness', 'live music', 'dancing', 'weekend drives']::TEXT[], ARRAY['mentorship', 'serious matches', 'premium experiences', 'respectful companionship']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5844, 557, true, 'silver', true, '2026-06-25T11:56:59+00', '2026-06-25T11:56:59+00', '2026-06-21T08:24:59+00'),
('seed+sugar_mummy-005@genuinesugarmummies.com', 'Monica Okello', '/seed/sugarmums/photo_12_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugarmums/photo_12_2026-06-25_14-22-09.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, well groomed, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, well groomed, generous. Preferred age range: 21-34.', 43, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254750703727', '+254750703727', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, well groomed, generous, kind', '21-34', ARRAY['coffee dates', 'cooking', 'spa days', 'fashion']::TEXT[], ARRAY['private dates', 'long-term arrangement', 'respectful companionship', 'lifestyle support']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 4777, 451, true, 'silver', true, '2026-06-25T11:49:59+00', '2026-06-25T11:49:59+00', '2026-06-20T07:24:59+00'),
('seed+sugar_mummy-006@genuinesugarmummies.com', 'Beatrice Chebet', '/seed/sugarmums/photo_13_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_13_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, generous, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, generous, kind. Preferred age range: 21-34.', 44, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254723355135', '+254723355135', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, generous, kind, well groomed', '21-34', ARRAY['fitness', 'travel', 'beach walks', 'fine dining']::TEXT[], ARRAY['premium experiences', 'meaningful conversations', 'discreet connection', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 4904, 458, true, 'silver', true, '2026-06-25T11:42:59+00', '2026-06-25T11:42:59+00', '2026-06-19T06:24:59+00'),
('seed+sugar_mummy-007@genuinesugarmummies.com', 'Caroline Johnson', '/seed/sugarmums/photo_14_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_14_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, honest. Preferred age range: 21-34.', 45, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254775303322', '+254775303322', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, generous, honest, discreet', '21-34', ARRAY['travel', 'beach walks', 'fitness', 'photography']::TEXT[], ARRAY['premium experiences', 'lifestyle support', 'serious matches', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 2942, 806, true, 'silver', true, '2026-06-25T11:35:59+00', '2026-06-25T11:35:59+00', '2026-06-18T05:24:59+00'),
('seed+sugar_mummy-008@genuinesugarmummies.com', 'Angela Taylor', '/seed/sugarmums/photo_15_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_15_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, generous. Preferred age range: 21-34.', 46, 'Jinja', 'Uganda', 'Jinja', '+256790618119', '+256790618119', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, serious about meeting, generous, well groomed', '21-34', ARRAY['cooking', 'spa days', 'weekend drives', 'live music']::TEXT[], ARRAY['private dates', 'meaningful conversations', 'mentorship', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6260, 487, true, 'silver', true, '2026-06-25T11:28:59+00', '2026-06-25T11:28:59+00', '2026-06-17T04:24:59+00'),
('seed+sugar_mummy-009@genuinesugarmummies.com', 'Florence Wanjiku', '/seed/sugarmums/photo_16_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_16_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, generous, serious about meeting. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, generous, serious about meeting. Preferred age range: 21-34.', 47, 'Mwanza', 'Tanzania', 'Mwanza', '+255790417530', '+255790417530', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, generous, serious about meeting, emotionally mature', '21-34', ARRAY['wine tasting', 'business events', 'spa days', 'dancing']::TEXT[], ARRAY['serious matches', 'premium experiences', 'verified members', 'private dates']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 2330, 827, true, 'silver', true, '2026-06-25T11:21:59+00', '2026-06-25T11:21:59+00', '2026-06-16T03:24:59+00'),
('seed+sugar_mummy-010@genuinesugarmummies.com', 'Jane Achieng', '/seed/sugarmums/photo_17_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_17_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, generous, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, generous, honest. Preferred age range: 21-34.', 48, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250786631699', '+250786631699', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, generous, honest, serious about meeting', '21-34', ARRAY['coffee dates', 'travel', 'fitness', 'art galleries']::TEXT[], ARRAY['discreet connection', 'respectful companionship', 'verified members', 'meaningful conversations']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 3870, 405, true, 'silver', true, '2026-06-25T11:14:59+00', '2026-06-25T11:14:59+00', '2026-06-15T02:24:59+00'),
('seed+sugar_mummy-011@genuinesugarmummies.com', 'Lucy Nabwire', '/seed/sugarmums/photo_18_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_18_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, respectful, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, respectful, well groomed. Preferred age range: 21-34.', 49, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254753849014', '+254753849014', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, respectful, well groomed, honest', '21-34', ARRAY['wine tasting', 'dancing', 'business events', 'spa days']::TEXT[], ARRAY['lifestyle support', 'premium experiences', 'discreet connection', 'mentorship']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 4213, 98, true, 'silver', true, '2026-06-25T11:07:59+00', '2026-06-25T11:07:59+00', '2026-06-14T01:24:59+00'),
('seed+sugar_mummy-012@genuinesugarmummies.com', 'Maryanne Mugisha', '/seed/sugarmums/photo_19_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_19_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, discreet, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, discreet, kind. Preferred age range: 21-34.', 50, 'Nairobi', 'Kenya', 'Nairobi', '+254753811875', '+254753811875', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, discreet, kind, emotionally mature', '21-34', ARRAY['live music', 'photography', 'art galleries', 'dancing']::TEXT[], ARRAY['verified members', 'serious matches', 'meaningful conversations', 'discreet connection']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 508, 624, true, 'silver', true, '2026-06-25T11:00:59+00', '2026-06-25T11:00:59+00', '2026-06-13T00:24:59+00'),
('seed+sugar_mummy-013@genuinesugarmummies.com', 'Rebecca Hassan', '/seed/sugarmums/photo_20_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_20_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, clean communication, consistent. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, clean communication, consistent. Preferred age range: 21-34.', 51, 'Mombasa', 'Kenya', 'Mombasa', '+254784795847', '+254784795847', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'serious about meeting, clean communication, consistent, respectful', '21-34', ARRAY['fashion', 'travel', 'coffee dates', 'spa days']::TEXT[], ARRAY['long-term arrangement', 'mentorship', 'verified members', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2945, 156, true, 'silver', true, '2026-06-25T10:53:59+00', '2026-06-25T10:53:59+00', '2026-06-11T23:24:59+00'),
('seed+sugar_mummy-014@genuinesugarmummies.com', 'Susan Wafula', '/seed/sugarmums/photo_22_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_22_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, clean communication, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, clean communication, generous. Preferred age range: 21-34.', 52, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254795543973', '+254795543973', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, clean communication, generous, serious about meeting', '21-34', ARRAY['weekend drives', 'business events', 'photography', 'travel']::TEXT[], ARRAY['mentorship', 'verified members', 'long-term arrangement', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3044, 532, true, 'silver', true, '2026-06-25T10:46:59+00', '2026-06-25T10:46:59+00', '2026-06-10T22:24:59+00'),
('seed+sugar_mummy-015@genuinesugarmummies.com', 'Teresa Smith', '/seed/sugarmums/photo_23_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_23_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, discreet. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, discreet. Preferred age range: 21-34.', 53, 'Thika', 'Kenya', 'Thika', '+254722632351', '+254722632351', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, generous, discreet, kind', '21-34', ARRAY['fitness', 'weekend drives', 'live music', 'fashion']::TEXT[], ARRAY['discreet connection', 'lifestyle support', 'verified members', 'private dates']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 4501, 801, true, 'silver', true, '2026-06-25T10:39:59+00', '2026-06-25T10:39:59+00', '2026-06-09T21:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
