-- Seed profiles, batch 3 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+mistress-025@genuinesugarmummies.com', 'Zara Mwangi', '/seed/mistresses/photo_37_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_37_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, honest, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, honest, respectful. Preferred age range: 38-68.', 28, 'Nairobi', 'Kenya', 'Nairobi', '+254719824586', '+254719824586', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'kind, honest, respectful, well groomed', '38-68', ARRAY['fine dining', 'fashion', 'dancing', 'weekend drives']::TEXT[], ARRAY['mentorship', 'meaningful conversations', 'discreet connection', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4549, 164, true, 'silver', true, '2026-06-25T09:29:59+00', '2026-06-25T09:29:59+00', '2026-05-31T11:24:59+00'),
('seed+mistress-026@genuinesugarmummies.com', 'Amara Kamau', '/seed/mistresses/photo_38_2026-06-24_14-00-45.jpg', ARRAY['/seed/mistresses/photo_38_2026-06-24_14-00-45.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, consistent, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, consistent, respectful. Preferred age range: 38-68.', 29, 'Nairobi', 'Kenya', 'Nairobi', '+254736815198', '+254736815198', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'discreet, consistent, respectful, clean communication', '38-68', ARRAY['cooking', 'fashion', 'business events', 'coffee dates']::TEXT[], ARRAY['meaningful conversations', 'long-term arrangement', 'serious matches', 'respectful companionship']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5543, 267, true, 'silver', true, '2026-06-25T09:22:59+00', '2026-06-25T09:22:59+00', '2026-05-30T10:24:59+00'),
('seed+mistress-027@genuinesugarmummies.com', 'Bella Kariuki', '/seed/mistresses/photo_39_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_39_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, serious about meeting, kind. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, serious about meeting, kind. Preferred age range: 38-68.', 21, 'Mombasa', 'Kenya', 'Mombasa', '+254732872343', '+254732872343', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, serious about meeting, kind, respectful', '38-68', ARRAY['fashion', 'dancing', 'coffee dates', 'beach walks']::TEXT[], ARRAY['serious matches', 'meaningful conversations', 'lifestyle support', 'long-term arrangement']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 6489, 352, true, 'silver', true, '2026-06-25T09:15:59+00', '2026-06-25T09:15:59+00', '2026-05-29T09:24:59+00'),
('seed+mistress-028@genuinesugarmummies.com', 'Chloe Nambooze', '/seed/mistresses/photo_3_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_3_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, well groomed, emotionally mature. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, well groomed, emotionally mature. Preferred age range: 38-68.', 22, 'Entebbe', 'Uganda', 'Entebbe', '+256768466643', '+256768466643', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'respectful, well groomed, emotionally mature, generous', '38-68', ARRAY['dancing', 'spa days', 'photography', 'live music']::TEXT[], ARRAY['mentorship', 'meaningful conversations', 'private dates', 'lifestyle support']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 6801, 324, true, 'silver', true, '2026-06-25T09:08:59+00', '2026-06-25T09:08:59+00', '2026-05-28T08:24:59+00'),
('seed+mistress-029@genuinesugarmummies.com', 'Deborah Nkurunziza', '/seed/mistresses/photo_40_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_40_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, premium experiences. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, discreet, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, premium experiences. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: generous, discreet, consistent. Preferred age range: 38-68.', 23, 'Dar es Salaam', 'Tanzania', 'Dar es Salaam', '+255775519093', '+255775519093', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'generous, discreet, consistent, well groomed', '38-68', ARRAY['live music', 'fine dining', 'spa days', 'wine tasting']::TEXT[], ARRAY['long-term arrangement', 'premium experiences', 'mentorship', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 6991, 707, true, 'silver', true, '2026-06-25T09:01:59+00', '2026-06-25T09:01:59+00', '2026-05-27T07:24:59+00'),
('seed+mistress-030@genuinesugarmummies.com', 'Esther Okello', '/seed/mistresses/photo_45_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_45_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: serious about meeting, kind, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: serious about meeting, kind, consistent. Preferred age range: 38-68.', 24, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250750557592', '+250750557592', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'serious about meeting, kind, consistent, well groomed', '38-68', ARRAY['fine dining', 'travel', 'fitness', 'weekend drives']::TEXT[], ARRAY['serious matches', 'mentorship', 'respectful companionship', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4269, 632, true, 'silver', true, '2026-06-25T08:54:59+00', '2026-06-25T08:54:59+00', '2026-05-26T06:24:59+00'),
('seed+mistress-031@genuinesugarmummies.com', 'Fiona Chebet', '/seed/mistresses/photo_4_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_4_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: respectful companionship, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, emotionally mature, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: respectful companionship, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: honest, emotionally mature, consistent. Preferred age range: 38-68.', 25, 'Mombasa', 'Kenya', 'Mombasa', '+254718796503', '+254718796503', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'honest, emotionally mature, consistent, serious about meeting', '38-68', ARRAY['beach walks', 'business events', 'live music', 'fitness']::TEXT[], ARRAY['respectful companionship', 'long-term arrangement', 'serious matches', 'mentorship']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5184, 350, true, 'silver', true, '2026-06-25T08:47:59+00', '2026-06-25T08:47:59+00', '2026-05-25T05:24:59+00'),
('seed+mistress-032@genuinesugarmummies.com', 'Gloria Johnson', '/seed/mistresses/photo_50_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_50_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, consistent, serious about meeting. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, consistent, serious about meeting. Preferred age range: 38-68.', 26, 'Thika', 'Kenya', 'Thika', '+254747681343', '+254747681343', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'kind, consistent, serious about meeting, honest', '38-68', ARRAY['spa days', 'cooking', 'travel', 'photography']::TEXT[], ARRAY['mentorship', 'verified members', 'serious matches', 'premium experiences']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 1651, 142, true, 'silver', true, '2026-06-25T08:40:59+00', '2026-06-25T08:40:59+00', '2026-05-24T04:24:59+00'),
('seed+mistress-033@genuinesugarmummies.com', 'Hilda Taylor', '/seed/mistresses/photo_5_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_5_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, discreet, honest. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, mentorship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, discreet, honest. Preferred age range: 38-68.', 27, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254765923927', '+254765923927', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'respectful, discreet, honest, generous', '38-68', ARRAY['spa days', 'beach walks', 'wine tasting', 'photography']::TEXT[], ARRAY['meaningful conversations', 'mentorship', 'long-term arrangement', 'verified members']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5049, 605, true, 'silver', true, '2026-06-25T08:33:59+00', '2026-06-25T08:33:59+00', '2026-05-23T03:24:59+00'),
('seed+mistress-034@genuinesugarmummies.com', 'Irene Wanjiku', '/seed/mistresses/photo_60_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_60_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, generous, discreet. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, generous, discreet. Preferred age range: 38-68.', 28, 'Thika', 'Kenya', 'Thika', '+254794763686', '+254794763686', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, generous, discreet, well groomed', '38-68', ARRAY['art galleries', 'wine tasting', 'cooking', 'spa days']::TEXT[], ARRAY['lifestyle support', 'verified members', 'discreet connection', 'long-term arrangement']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 2825, 646, true, 'silver', true, '2026-06-25T08:26:59+00', '2026-06-25T08:26:59+00', '2026-05-22T02:24:59+00'),
('seed+mistress-035@genuinesugarmummies.com', 'Jackie Achieng', '/seed/mistresses/photo_61_2026-06-24_14-00-45.jpg', ARRAY['/seed/mistresses/photo_61_2026-06-24_14-00-45.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, serious about meeting, emotionally mature. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: mentorship, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: respectful, serious about meeting, emotionally mature. Preferred age range: 38-68.', 29, 'Mombasa', 'Kenya', 'Mombasa', '+254788991014', '+254788991014', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'respectful, serious about meeting, emotionally mature, well groomed', '38-68', ARRAY['cooking', 'dancing', 'live music', 'spa days']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'verified members', 'private dates']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 676, 798, true, 'silver', true, '2026-06-25T08:19:59+00', '2026-06-25T08:19:59+00', '2026-05-21T01:24:59+00'),
('seed+mistress-036@genuinesugarmummies.com', 'Kendra Nabwire', '/seed/mistresses/photo_62_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_62_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, respectful, generous. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, respectful, generous. Preferred age range: 38-68.', 21, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254764329471', '+254764329471', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, respectful, generous, kind', '38-68', ARRAY['beach walks', 'spa days', 'business events', 'live music']::TEXT[], ARRAY['long-term arrangement', 'discreet connection', 'serious matches', 'private dates']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 6667, 192, true, 'silver', true, '2026-06-25T08:12:59+00', '2026-06-25T08:12:59+00', '2026-05-20T00:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
