-- Seed profiles, batch 12 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-040@genuinesugarmummies.com', 'Wairimu Smith', '/seed/sugarmums/photo_44_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_44_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, kind, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, kind, clean communication. Preferred age range: 21-34.', 57, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250757639995', '+250757639995', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, kind, clean communication, honest', '21-34', ARRAY['art galleries', 'live music', 'fashion', 'business events']::TEXT[], ARRAY['meaningful conversations', 'premium experiences', 'verified members', 'discreet connection']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 949, 587, true, 'silver', true, '2026-06-25T07:44:59+00', '2026-06-25T07:44:59+00', '2026-05-15T20:24:59+00'),
('seed+sugar_mummy-041@genuinesugarmummies.com', 'Yolanda Brown', '/seed/sugarmums/photo_46_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_46_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, kind, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, kind, honest. Preferred age range: 21-34.', 58, 'Nakuru', 'Kenya', 'Nakuru', '+254730952993', '+254730952993', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, kind, honest, generous', '21-34', ARRAY['art galleries', 'travel', 'fitness', 'wine tasting']::TEXT[], ARRAY['lifestyle support', 'meaningful conversations', 'private dates', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4812, 347, true, 'silver', true, '2026-06-25T07:37:59+00', '2026-06-25T07:37:59+00', '2026-05-14T19:24:59+00'),
('seed+sugar_mummy-042@genuinesugarmummies.com', 'Zipporah Otieno', '/seed/sugarmums/photo_47_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_47_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, generous, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, generous, kind. Preferred age range: 21-34.', 38, 'Nakuru', 'Kenya', 'Nakuru', '+254768352422', '+254768352422', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, generous, kind, discreet', '21-34', ARRAY['dancing', 'weekend drives', 'art galleries', 'coffee dates']::TEXT[], ARRAY['discreet connection', 'serious matches', 'mentorship', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4858, 232, true, 'silver', true, '2026-06-25T07:30:59+00', '2026-06-25T07:30:59+00', '2026-05-13T18:24:59+00'),
('seed+sugar_mummy-043@genuinesugarmummies.com', 'Margaret Njeri', '/seed/sugarmums/photo_48_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_48_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, kind, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, kind, clean communication. Preferred age range: 21-34.', 39, 'Nairobi', 'Kenya', 'Nairobi', '+254756900961', '+254756900961', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, kind, clean communication, well groomed', '21-34', ARRAY['fine dining', 'fitness', 'art galleries', 'business events']::TEXT[], ARRAY['discreet connection', 'mentorship', 'respectful companionship', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3077, 424, true, 'silver', true, '2026-06-25T07:23:59+00', '2026-06-25T07:23:59+00', '2026-05-12T17:24:59+00'),
('seed+sugar_mummy-044@genuinesugarmummies.com', 'Catherine Mutiso', '/seed/sugarmums/photo_49_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_49_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, honest, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, honest, well groomed. Preferred age range: 21-34.', 40, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254780393308', '+254780393308', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, honest, well groomed, serious about meeting', '21-34', ARRAY['fine dining', 'business events', 'coffee dates', 'live music']::TEXT[], ARRAY['premium experiences', 'verified members', 'mentorship', 'respectful companionship']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5185, 857, true, 'silver', true, '2026-06-25T07:16:59+00', '2026-06-25T07:16:59+00', '2026-05-11T16:24:59+00'),
('seed+sugar_mummy-045@genuinesugarmummies.com', 'Janet Kato', '/seed/sugarmums/photo_4_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_4_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, honest, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, honest, kind. Preferred age range: 21-34.', 41, 'Kisumu', 'Kenya', 'Kisumu', '+254715147504', '+254715147504', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'serious about meeting, honest, kind, discreet', '21-34', ARRAY['travel', 'beach walks', 'fashion', 'dancing']::TEXT[], ARRAY['verified members', 'premium experiences', 'meaningful conversations', 'private dates']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 1202, 51, true, 'silver', true, '2026-06-25T07:09:59+00', '2026-06-25T07:09:59+00', '2026-05-10T15:24:59+00'),
('seed+sugar_mummy-046@genuinesugarmummies.com', 'Rosemary Mutesi', '/seed/sugarmums/photo_4_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugarmums/photo_4_2026-06-25_14-22-09.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, clean communication, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, clean communication, kind. Preferred age range: 21-34.', 42, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254748722565', '+254748722565', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, clean communication, kind, discreet', '21-34', ARRAY['coffee dates', 'art galleries', 'weekend drives', 'business events']::TEXT[], ARRAY['verified members', 'meaningful conversations', 'premium experiences', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4235, 356, true, 'silver', true, '2026-06-25T07:02:59+00', '2026-06-25T07:02:59+00', '2026-05-09T14:24:59+00'),
('seed+sugar_mummy-047@genuinesugarmummies.com', 'Monica Kimani', '/seed/sugarmums/photo_51_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_51_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, respectful, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, respectful, well groomed. Preferred age range: 21-34.', 43, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254793920934', '+254793920934', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, respectful, well groomed, clean communication', '21-34', ARRAY['fitness', 'art galleries', 'fine dining', 'fashion']::TEXT[], ARRAY['premium experiences', 'private dates', 'long-term arrangement', 'mentorship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 4818, 806, true, 'silver', true, '2026-06-25T06:55:59+00', '2026-06-25T06:55:59+00', '2026-05-08T13:24:59+00'),
('seed+sugar_mummy-048@genuinesugarmummies.com', 'Beatrice Maina', '/seed/sugarmums/photo_52_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_52_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, respectful, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, respectful, generous. Preferred age range: 21-34.', 44, 'Jinja', 'Uganda', 'Jinja', '+256712562462', '+256712562462', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'emotionally mature, respectful, generous, well groomed', '21-34', ARRAY['fine dining', 'business events', 'art galleries', 'weekend drives']::TEXT[], ARRAY['verified members', 'long-term arrangement', 'meaningful conversations', 'serious matches']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3510, 333, true, 'silver', true, '2026-06-25T06:48:59+00', '2026-06-25T06:48:59+00', '2026-05-08T12:24:59+00'),
('seed+sugar_mummy-049@genuinesugarmummies.com', 'Caroline Williams', '/seed/sugarmums/photo_53_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_53_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, honest, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, honest, emotionally mature. Preferred age range: 21-34.', 45, 'Arusha', 'Tanzania', 'Arusha', '+255751794395', '+255751794395', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, honest, emotionally mature, discreet', '21-34', ARRAY['photography', 'live music', 'beach walks', 'coffee dates']::TEXT[], ARRAY['serious matches', 'discreet connection', 'respectful companionship', 'premium experiences']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 4384, 501, true, 'silver', true, '2026-06-25T06:41:59+00', '2026-06-25T06:41:59+00', '2026-05-07T11:24:59+00'),
('seed+sugar_mummy-050@genuinesugarmummies.com', 'Angela Mwangi', '/seed/sugarmums/photo_54_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_54_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, emotionally mature, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, emotionally mature, honest. Preferred age range: 21-34.', 46, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250781412999', '+250781412999', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, emotionally mature, honest, clean communication', '21-34', ARRAY['weekend drives', 'art galleries', 'coffee dates', 'fashion']::TEXT[], ARRAY['verified members', 'premium experiences', 'mentorship', 'discreet connection']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 2518, 242, true, 'silver', true, '2026-06-25T06:34:59+00', '2026-06-25T06:34:59+00', '2026-05-06T10:24:59+00'),
('seed+sugar_mummy-051@genuinesugarmummies.com', 'Florence Kamau', '/seed/sugarmums/photo_55_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_55_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, honest, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, honest, kind. Preferred age range: 21-34.', 47, 'Nakuru', 'Kenya', 'Nakuru', '+254754910616', '+254754910616', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, honest, kind, emotionally mature', '21-34', ARRAY['photography', 'wine tasting', 'art galleries', 'fashion']::TEXT[], ARRAY['discreet connection', 'premium experiences', 'mentorship', 'meaningful conversations']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1279, 835, true, 'silver', true, '2026-06-25T06:27:59+00', '2026-06-25T06:27:59+00', '2026-05-05T09:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
