-- Seed profiles, batch 10 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-016@genuinesugarmummies.com', 'Victoria Brown', '/seed/sugarmums/photo_24_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_24_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, well groomed. Preferred age range: 21-34.', 54, 'Thika', 'Kenya', 'Thika', '+254762481995', '+254762481995', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, serious about meeting, well groomed, respectful', '21-34', ARRAY['wine tasting', 'dancing', 'business events', 'weekend drives']::TEXT[], ARRAY['serious matches', 'long-term arrangement', 'meaningful conversations', 'private dates']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5974, 704, true, 'silver', true, '2026-06-25T10:32:59+00', '2026-06-25T10:32:59+00', '2026-06-08T20:24:59+00'),
('seed+sugar_mummy-017@genuinesugarmummies.com', 'Agnes Otieno', '/seed/sugarmums/photo_26_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_26_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, emotionally mature, consistent. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, emotionally mature, consistent. Preferred age range: 21-34.', 55, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254783561999', '+254783561999', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, emotionally mature, consistent, serious about meeting', '21-34', ARRAY['business events', 'fitness', 'dancing', 'photography']::TEXT[], ARRAY['discreet connection', 'lifestyle support', 'verified members', 'meaningful conversations']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 6383, 484, true, 'silver', true, '2026-06-25T10:25:59+00', '2026-06-25T10:25:59+00', '2026-06-07T19:24:59+00'),
('seed+sugar_mummy-018@genuinesugarmummies.com', 'Dorothy Njeri', '/seed/sugarmums/photo_27_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_27_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, consistent, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, consistent, generous. Preferred age range: 21-34.', 56, 'Entebbe', 'Uganda', 'Entebbe', '+256776992512', '+256776992512', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, consistent, generous, honest', '21-34', ARRAY['coffee dates', 'wine tasting', 'beach walks', 'weekend drives']::TEXT[], ARRAY['lifestyle support', 'meaningful conversations', 'mentorship', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2415, 139, true, 'silver', true, '2026-06-25T10:18:59+00', '2026-06-25T10:18:59+00', '2026-06-06T18:24:59+00'),
('seed+sugar_mummy-019@genuinesugarmummies.com', 'Elizabeth Mutiso', '/seed/sugarmums/photo_28_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_28_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, consistent, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, consistent, respectful. Preferred age range: 21-34.', 57, 'Dar es Salaam', 'Tanzania', 'Dar es Salaam', '+255716515712', '+255716515712', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, consistent, respectful, emotionally mature', '21-34', ARRAY['fitness', 'art galleries', 'coffee dates', 'weekend drives']::TEXT[], ARRAY['long-term arrangement', 'private dates', 'lifestyle support', 'serious matches']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 3143, 526, true, 'silver', true, '2026-06-25T10:11:59+00', '2026-06-25T10:11:59+00', '2026-06-05T17:24:59+00'),
('seed+sugar_mummy-020@genuinesugarmummies.com', 'Hellen Kato', '/seed/sugarmums/photo_29_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_29_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, serious about meeting, respectful. Preferred age range: 21-34.', 58, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250770829884', '+250770829884', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, serious about meeting, respectful, honest', '21-34', ARRAY['travel', 'fashion', 'live music', 'fine dining']::TEXT[], ARRAY['premium experiences', 'private dates', 'serious matches', 'long-term arrangement']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 1216, 863, true, 'silver', true, '2026-06-25T10:04:59+00', '2026-06-25T10:04:59+00', '2026-06-04T16:24:59+00'),
('seed+sugar_mummy-021@genuinesugarmummies.com', 'Judith Mutesi', '/seed/sugarmums/photo_30_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_30_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, honest, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: serious about meeting, honest, kind. Preferred age range: 21-34.', 38, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254746349183', '+254746349183', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'serious about meeting, honest, kind, respectful', '21-34', ARRAY['business events', 'fine dining', 'travel', 'cooking']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'meaningful conversations', 'serious matches']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 1078, 320, true, 'silver', true, '2026-06-25T09:57:59+00', '2026-06-25T09:57:59+00', '2026-06-03T15:24:59+00'),
('seed+sugar_mummy-022@genuinesugarmummies.com', 'Pauline Kimani', '/seed/sugarmums/photo_31_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_31_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, honest, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, honest, respectful. Preferred age range: 21-34.', 39, 'Nakuru', 'Kenya', 'Nakuru', '+254775702980', '+254775702980', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, honest, respectful, consistent', '21-34', ARRAY['beach walks', 'spa days', 'dancing', 'business events']::TEXT[], ARRAY['discreet connection', 'private dates', 'verified members', 'long-term arrangement']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5966, 259, true, 'silver', true, '2026-06-25T09:50:59+00', '2026-06-25T09:50:59+00', '2026-06-02T14:24:59+00'),
('seed+sugar_mummy-023@genuinesugarmummies.com', 'Regina Maina', '/seed/sugarmums/photo_31_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_31_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, honest, consistent. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, honest, consistent. Preferred age range: 21-34.', 40, 'Eldoret', 'Kenya', 'Eldoret', '+254777670511', '+254777670511', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, honest, consistent, respectful', '21-34', ARRAY['beach walks', 'fine dining', 'business events', 'fashion']::TEXT[], ARRAY['lifestyle support', 'long-term arrangement', 'meaningful conversations', 'premium experiences']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 6522, 531, true, 'silver', true, '2026-06-25T09:43:59+00', '2026-06-25T09:43:59+00', '2026-06-01T13:24:59+00'),
('seed+sugar_mummy-024@genuinesugarmummies.com', 'Sophia Williams', '/seed/sugarmums/photo_32_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_32_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, consistent, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, consistent, generous. Preferred age range: 21-34.', 41, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254740868544', '+254740868544', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, consistent, generous, clean communication', '21-34', ARRAY['cooking', 'art galleries', 'fine dining', 'spa days']::TEXT[], ARRAY['long-term arrangement', 'premium experiences', 'mentorship', 'verified members']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5226, 684, true, 'silver', true, '2026-06-25T09:36:59+00', '2026-06-25T09:36:59+00', '2026-06-01T12:24:59+00'),
('seed+sugar_mummy-025@genuinesugarmummies.com', 'Anne Mwangi', '/seed/sugarmums/photo_32_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_32_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, well groomed, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, well groomed, honest. Preferred age range: 21-34.', 42, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254733950916', '+254733950916', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, well groomed, honest, consistent', '21-34', ARRAY['photography', 'dancing', 'fashion', 'weekend drives']::TEXT[], ARRAY['respectful companionship', 'premium experiences', 'verified members', 'long-term arrangement']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 596, 150, true, 'silver', true, '2026-06-25T09:29:59+00', '2026-06-25T09:29:59+00', '2026-05-31T11:24:59+00'),
('seed+sugar_mummy-026@genuinesugarmummies.com', 'Christine Kamau', '/seed/sugarmums/photo_33_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_33_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, honest, well groomed. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, honest, well groomed. Preferred age range: 21-34.', 43, 'Nairobi', 'Kenya', 'Nairobi', '+254714889882', '+254714889882', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, honest, well groomed, clean communication', '21-34', ARRAY['fitness', 'live music', 'fine dining', 'cooking']::TEXT[], ARRAY['respectful companionship', 'premium experiences', 'mentorship', 'discreet connection']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 1645, 674, true, 'silver', true, '2026-06-25T09:22:59+00', '2026-06-25T09:22:59+00', '2026-05-30T10:24:59+00'),
('seed+sugar_mummy-027@genuinesugarmummies.com', 'Doreen Kariuki', '/seed/sugarmums/photo_33_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_33_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, kind, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, kind, honest. Preferred age range: 21-34.', 44, 'Thika', 'Kenya', 'Thika', '+254766505426', '+254766505426', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, kind, honest, serious about meeting', '21-34', ARRAY['cooking', 'dancing', 'fine dining', 'spa days']::TEXT[], ARRAY['premium experiences', 'mentorship', 'private dates', 'long-term arrangement']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1610, 359, true, 'silver', true, '2026-06-25T09:15:59+00', '2026-06-25T09:15:59+00', '2026-05-29T09:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
