-- Seed profiles, batch 15 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-076@genuinesugarmummies.com', 'Lydia Kamau', '/seed/sugarmums/photo_86_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_86_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, honest, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, honest, kind. Preferred age range: 21-34.', 51, 'Nairobi', 'Kenya', 'Nairobi', '+254712655134', '+254712655134', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, honest, kind, serious about meeting', '21-34', ARRAY['live music', 'coffee dates', 'art galleries', 'fashion']::TEXT[], ARRAY['respectful companionship', 'discreet connection', 'verified members', 'serious matches']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 2330, 751, true, 'silver', true, '2026-06-25T03:32:59+00', '2026-06-25T03:32:59+00', '2026-04-10T08:24:59+00'),
('seed+sugar_mummy-077@genuinesugarmummies.com', 'Martha Kariuki', '/seed/sugarmums/photo_87_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_87_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, clean communication, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, clean communication, emotionally mature. Preferred age range: 21-34.', 52, 'Nairobi', 'Kenya', 'Nairobi', '+254789652029', '+254789652029', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, clean communication, emotionally mature, generous', '21-34', ARRAY['coffee dates', 'cooking', 'photography', 'spa days']::TEXT[], ARRAY['long-term arrangement', 'meaningful conversations', 'private dates', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6758, 270, true, 'silver', true, '2026-06-25T03:25:59+00', '2026-06-25T03:25:59+00', '2026-04-09T07:24:59+00'),
('seed+sugar_mummy-078@genuinesugarmummies.com', 'Naomi Nambooze', '/seed/sugarmums/photo_88_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_88_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, discreet, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, discreet, generous. Preferred age range: 21-34.', 53, 'Entebbe', 'Uganda', 'Entebbe', '+256793896483', '+256793896483', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'emotionally mature, discreet, generous, consistent', '21-34', ARRAY['dancing', 'beach walks', 'travel', 'fashion']::TEXT[], ARRAY['long-term arrangement', 'discreet connection', 'lifestyle support', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 845, 44, true, 'silver', true, '2026-06-25T03:18:59+00', '2026-06-25T03:18:59+00', '2026-04-08T06:24:59+00'),
('seed+sugar_mummy-079@genuinesugarmummies.com', 'Priscilla Nkurunziza', '/seed/sugarmums/photo_89_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_89_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, consistent, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, consistent, generous. Preferred age range: 21-34.', 54, 'Arusha', 'Tanzania', 'Arusha', '+255715340927', '+255715340927', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, consistent, generous, discreet', '21-34', ARRAY['beach walks', 'coffee dates', 'art galleries', 'fine dining']::TEXT[], ARRAY['respectful companionship', 'meaningful conversations', 'private dates', 'lifestyle support']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 7463, 228, true, 'silver', true, '2026-06-25T03:11:59+00', '2026-06-25T03:11:59+00', '2026-04-07T05:24:59+00'),
('seed+sugar_mummy-080@genuinesugarmummies.com', 'Sarah Okello', '/seed/sugarmums/photo_90_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_90_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, respectful, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: verified members, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, respectful, emotionally mature. Preferred age range: 21-34.', 55, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250728888795', '+250728888795', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, respectful, emotionally mature, discreet', '21-34', ARRAY['fine dining', 'travel', 'spa days', 'fitness']::TEXT[], ARRAY['verified members', 'respectful companionship', 'meaningful conversations', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 5918, 852, true, 'silver', true, '2026-06-25T03:04:59+00', '2026-06-25T03:04:59+00', '2026-04-06T04:24:59+00'),
('seed+sugar_mummy-081@genuinesugarmummies.com', 'Tabitha Chebet', '/seed/sugarmums/photo_91_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_91_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, consistent. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, consistent. Preferred age range: 21-34.', 56, 'Mombasa', 'Kenya', 'Mombasa', '+254722558320', '+254722558320', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, generous, consistent, respectful', '21-34', ARRAY['fitness', 'weekend drives', 'business events', 'live music']::TEXT[], ARRAY['serious matches', 'long-term arrangement', 'premium experiences', 'lifestyle support']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 6950, 249, true, 'silver', true, '2026-06-25T02:57:59+00', '2026-06-25T02:57:59+00', '2026-04-05T03:24:59+00'),
('seed+sugar_mummy-082@genuinesugarmummies.com', 'Wairimu Johnson', '/seed/sugarmums/photo_93_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_93_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, honest. Preferred age range: 21-34.', 57, 'Thika', 'Kenya', 'Thika', '+254755679902', '+254755679902', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, well groomed, honest, generous', '21-34', ARRAY['business events', 'dancing', 'wine tasting', 'cooking']::TEXT[], ARRAY['long-term arrangement', 'premium experiences', 'respectful companionship', 'verified members']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 3617, 396, true, 'silver', true, '2026-06-25T02:50:59+00', '2026-06-25T02:50:59+00', '2026-04-04T02:24:59+00'),
('seed+sugar_mummy-083@genuinesugarmummies.com', 'Yolanda Taylor', '/seed/sugarmums/photo_94_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_94_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, clean communication, kind. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, clean communication, kind. Preferred age range: 21-34.', 58, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254791261771', '+254791261771', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, clean communication, kind, consistent', '21-34', ARRAY['spa days', 'beach walks', 'travel', 'business events']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'private dates', 'respectful companionship']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3271, 769, true, 'silver', true, '2026-06-25T02:43:59+00', '2026-06-25T02:43:59+00', '2026-04-03T01:24:59+00'),
('seed+sugar_mummy-084@genuinesugarmummies.com', 'Zipporah Wanjiku', '/seed/sugarmums/photo_95_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_95_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, serious about meeting. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, generous, serious about meeting. Preferred age range: 21-34.', 38, 'Thika', 'Kenya', 'Thika', '+254767684041', '+254767684041', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, generous, serious about meeting, emotionally mature', '21-34', ARRAY['travel', 'wine tasting', 'fine dining', 'fitness']::TEXT[], ARRAY['discreet connection', 'premium experiences', 'mentorship', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4277, 580, true, 'silver', true, '2026-06-25T02:36:59+00', '2026-06-25T02:36:59+00', '2026-04-02T00:24:59+00'),
('seed+sugar_mummy-085@genuinesugarmummies.com', 'Margaret Achieng', '/seed/sugarmums/photo_96_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_96_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, kind, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, kind, honest. Preferred age range: 21-34.', 39, 'Mombasa', 'Kenya', 'Mombasa', '+254720860053', '+254720860053', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, kind, honest, well groomed', '21-34', ARRAY['fine dining', 'travel', 'fashion', 'coffee dates']::TEXT[], ARRAY['private dates', 'premium experiences', 'long-term arrangement', 'respectful companionship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 7495, 584, true, 'silver', true, '2026-06-25T02:29:59+00', '2026-06-25T02:29:59+00', '2026-03-31T23:24:59+00'),
('seed+sugar_mummy-086@genuinesugarmummies.com', 'Catherine Nabwire', '/seed/sugarmums/photo_97_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_97_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, clean communication. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: meaningful conversations, serious matches. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, clean communication. Preferred age range: 21-34.', 40, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254731555791', '+254731555791', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, well groomed, clean communication, respectful', '21-34', ARRAY['coffee dates', 'weekend drives', 'spa days', 'beach walks']::TEXT[], ARRAY['meaningful conversations', 'serious matches', 'mentorship', 'verified members']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3529, 294, true, 'silver', true, '2026-06-25T02:22:59+00', '2026-06-25T02:22:59+00', '2026-03-30T22:24:59+00'),
('seed+sugar_mummy-087@genuinesugarmummies.com', 'Janet Mugisha', '/seed/sugarmums/photo_98_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_98_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, clean communication, discreet. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, discreet connection. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, clean communication, discreet. Preferred age range: 21-34.', 41, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254760448354', '+254760448354', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, clean communication, discreet, respectful', '21-34', ARRAY['dancing', 'travel', 'fashion', 'fitness']::TEXT[], ARRAY['lifestyle support', 'discreet connection', 'serious matches', 'verified members']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5160, 873, true, 'silver', true, '2026-06-25T02:15:59+00', '2026-06-25T02:15:59+00', '2026-03-29T21:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
