-- Seed profiles, batch 4 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+mistress-037@genuinesugarmummies.com', 'Lilian Mugisha', '/seed/mistresses/photo_65_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_65_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, honest, consistent. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: well groomed, honest, consistent. Preferred age range: 38-68.', 22, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254766742412', '+254766742412', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'well groomed, honest, consistent, kind', '38-68', ARRAY['art galleries', 'fine dining', 'coffee dates', 'live music']::TEXT[], ARRAY['private dates', 'discreet connection', 'meaningful conversations', 'long-term arrangement']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5972, 846, true, 'silver', true, '2026-06-25T08:05:59+00', '2026-06-25T08:05:59+00', '2026-05-18T23:24:59+00'),
('seed+mistress-038@genuinesugarmummies.com', 'Mercy Hassan', '/seed/mistresses/photo_6_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_6_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, discreet, well groomed. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: meaningful conversations, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, discreet, well groomed. Preferred age range: 38-68.', 23, 'Jinja', 'Uganda', 'Jinja', '+256740387936', '+256740387936', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'emotionally mature, discreet, well groomed, consistent', '38-68', ARRAY['beach walks', 'cooking', 'coffee dates', 'art galleries']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'verified members', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 714, 462, true, 'silver', true, '2026-06-25T07:58:59+00', '2026-06-25T07:58:59+00', '2026-05-17T22:24:59+00'),
('seed+mistress-039@genuinesugarmummies.com', 'Nelly Wafula', '/seed/mistresses/photo_75_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_75_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, emotionally mature, kind. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, emotionally mature, kind. Preferred age range: 38-68.', 24, 'Mwanza', 'Tanzania', 'Mwanza', '+255729840734', '+255729840734', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, emotionally mature, kind, consistent', '38-68', ARRAY['fitness', 'live music', 'wine tasting', 'fashion']::TEXT[], ARRAY['premium experiences', 'verified members', 'private dates', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 606, 231, true, 'silver', true, '2026-06-25T07:51:59+00', '2026-06-25T07:51:59+00', '2026-05-16T21:24:59+00'),
('seed+mistress-040@genuinesugarmummies.com', 'Opal Smith', '/seed/mistresses/photo_7_2026-06-24_14-00-45.jpg', ARRAY['/seed/mistresses/photo_7_2026-06-24_14-00-45.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, serious about meeting, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, serious about meeting, respectful. Preferred age range: 38-68.', 25, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250783498858', '+250783498858', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'kind, serious about meeting, respectful, honest', '38-68', ARRAY['beach walks', 'fashion', 'coffee dates', 'art galleries']::TEXT[], ARRAY['long-term arrangement', 'respectful companionship', 'lifestyle support', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 128, 500, true, 'silver', true, '2026-06-25T07:44:59+00', '2026-06-25T07:44:59+00', '2026-05-15T20:24:59+00'),
('seed+mistress-041@genuinesugarmummies.com', 'Pearl Brown', '/seed/mistresses/photo_7_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_7_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, serious matches. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, discreet, kind. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: verified members, serious matches. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, discreet, kind. Preferred age range: 38-68.', 26, 'Thika', 'Kenya', 'Thika', '+254713507746', '+254713507746', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'emotionally mature, discreet, kind, serious about meeting', '38-68', ARRAY['fitness', 'dancing', 'beach walks', 'cooking']::TEXT[], ARRAY['verified members', 'serious matches', 'lifestyle support', 'discreet connection']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5559, 356, true, 'silver', true, '2026-06-25T07:37:59+00', '2026-06-25T07:37:59+00', '2026-05-14T19:24:59+00'),
('seed+mistress-042@genuinesugarmummies.com', 'Rachel Otieno', '/seed/mistresses/photo_81_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_81_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: serious about meeting, respectful, generous. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, verified members. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: serious about meeting, respectful, generous. Preferred age range: 38-68.', 27, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254764242291', '+254764242291', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'serious about meeting, respectful, generous, consistent', '38-68', ARRAY['photography', 'weekend drives', 'art galleries', 'cooking']::TEXT[], ARRAY['serious matches', 'verified members', 'respectful companionship', 'lifestyle support']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 3862, 899, true, 'silver', true, '2026-06-25T07:30:59+00', '2026-06-25T07:30:59+00', '2026-05-13T18:24:59+00'),
('seed+mistress-043@genuinesugarmummies.com', 'Sandra Njeri', '/seed/mistresses/photo_84_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_84_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, discreet, serious about meeting. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: lifestyle support, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: kind, discreet, serious about meeting. Preferred age range: 38-68.', 28, 'Kisumu', 'Kenya', 'Kisumu', '+254720593152', '+254720593152', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'kind, discreet, serious about meeting, clean communication', '38-68', ARRAY['fine dining', 'fitness', 'beach walks', 'fashion']::TEXT[], ARRAY['lifestyle support', 'discreet connection', 'premium experiences', 'meaningful conversations']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 6216, 31, true, 'silver', true, '2026-06-25T07:23:59+00', '2026-06-25T07:23:59+00', '2026-05-12T17:24:59+00'),
('seed+mistress-044@genuinesugarmummies.com', 'Tracy Mutiso', '/seed/mistresses/photo_8_2026-06-24_14-00-45.jpg', ARRAY['/seed/mistresses/photo_8_2026-06-24_14-00-45.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, respectful, clean communication. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: private dates, respectful companionship. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, respectful, clean communication. Preferred age range: 38-68.', 29, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254726596564', '+254726596564', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'emotionally mature, respectful, clean communication, generous', '38-68', ARRAY['fine dining', 'fashion', 'live music', 'spa days']::TEXT[], ARRAY['private dates', 'respectful companionship', 'verified members', 'serious matches']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 1017, 697, true, 'silver', true, '2026-06-25T07:16:59+00', '2026-06-25T07:16:59+00', '2026-05-11T16:24:59+00'),
('seed+mistress-045@genuinesugarmummies.com', 'Vera Kato', '/seed/mistresses/photo_8_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_8_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, discreet, generous. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: premium experiences, meaningful conversations. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: clean communication, discreet, generous. Preferred age range: 38-68.', 21, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254713427110', '+254713427110', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'clean communication, discreet, generous, honest', '38-68', ARRAY['live music', 'art galleries', 'photography', 'fitness']::TEXT[], ARRAY['premium experiences', 'meaningful conversations', 'private dates', 'long-term arrangement']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5628, 601, true, 'silver', true, '2026-06-25T07:09:59+00', '2026-06-25T07:09:59+00', '2026-05-10T15:24:59+00'),
('seed+mistress-046@genuinesugarmummies.com', 'Wanja Mutesi', '/seed/mistresses/photo_92_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_92_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, generous, respectful. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: serious matches, lifestyle support. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: discreet, generous, respectful. Preferred age range: 38-68.', 22, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254778549186', '+254778549186', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'discreet, generous, respectful, clean communication', '38-68', ARRAY['beach walks', 'photography', 'live music', 'travel']::TEXT[], ARRAY['serious matches', 'lifestyle support', 'private dates', 'premium experiences']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 3115, 689, true, 'silver', true, '2026-06-25T07:02:59+00', '2026-06-25T07:02:59+00', '2026-05-09T14:24:59+00'),
('seed+mistress-047@genuinesugarmummies.com', 'Yasmin Kimani', '/seed/mistresses/photo_99_2026-06-25_14-21-42.jpg', ARRAY['/seed/mistresses/photo_99_2026-06-25_14-21-42.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, well groomed, clean communication. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: long-term arrangement, discreet connection. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: consistent, well groomed, clean communication. Preferred age range: 38-68.', 23, 'Mombasa', 'Kenya', 'Mombasa', '+254732869440', '+254732869440', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'consistent, well groomed, clean communication, emotionally mature', '38-68', ARRAY['coffee dates', 'spa days', 'fashion', 'fine dining']::TEXT[], ARRAY['long-term arrangement', 'discreet connection', 'private dates', 'lifestyle support']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 5408, 546, true, 'silver', true, '2026-06-25T06:55:59+00', '2026-06-25T06:55:59+00', '2026-05-08T13:24:59+00'),
('seed+mistress-048@genuinesugarmummies.com', 'Zuri Maina', '/seed/mistresses/photo_9_2026-06-25_14-21-41.jpg', ARRAY['/seed/mistresses/photo_9_2026-06-25_14-21-41.jpg']::TEXT[], 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: discreet connection, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, generous, discreet. Preferred age range: 38-68.', 'Adult mistress with a polished, youthful style and a preference for respectful, established men. Interests: discreet connection, long-term arrangement. Wants: A generous sugar daddy for discreet dates, lifestyle support, and consistent communication. Needed qualities: emotionally mature, generous, discreet. Preferred age range: 38-68.', 24, 'Entebbe', 'Uganda', 'Entebbe', '+256741886931', '+256741886931', 'mistress', 'mistress', 'Sugar Daddy', 'I am a mistress looking for Sugar Daddy.', 'A generous sugar daddy for discreet dates, lifestyle support, and consistent communication.', 'emotionally mature, generous, discreet, serious about meeting', '38-68', ARRAY['business events', 'dancing', 'coffee dates', 'art galleries']::TEXT[], ARRAY['discreet connection', 'long-term arrangement', 'mentorship', 'meaningful conversations']::TEXT[], 'Slim', 'silver', true, 'verified', true, false, false, 4748, 487, true, 'silver', true, '2026-06-25T06:48:59+00', '2026-06-25T06:48:59+00', '2026-05-08T12:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
