-- Seed profiles, batch 5 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_daddy-001@genuinesugarmummies.com', 'James Kamau', '/seed/sugar-dads/photo_10_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_10_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, consistent, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: meaningful conversations, discreet connection. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, consistent, serious about meeting. Preferred age range: 21-35.', 43, 'Manchester', 'United Kingdom', 'Manchester', '+447818389688', '+447818389688', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, consistent, serious about meeting, well groomed', '21-35', ARRAY['fashion', 'fine dining', 'art galleries', 'wine tasting']::TEXT[], ARRAY['meaningful conversations', 'discreet connection', 'lifestyle support', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 163, 581, true, 'silver', true, '2026-06-25T12:17:59+00', '2026-06-25T12:17:59+00', '2026-06-24T11:24:59+00'),
('seed+sugar_daddy-002@genuinesugarmummies.com', 'Robert Kariuki', '/seed/sugar-dads/photo_11_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_11_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, serious about meeting, honest. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, serious about meeting, honest. Preferred age range: 21-35.', 44, 'New York', 'United States', 'New York', '+12022144646', '+12022144646', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, serious about meeting, honest, kind', '21-35', ARRAY['travel', 'live music', 'photography', 'beach walks']::TEXT[], ARRAY['discreet connection', 'verified members', 'lifestyle support', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2490, 107, true, 'silver', true, '2026-06-25T12:10:59+00', '2026-06-25T12:10:59+00', '2026-06-23T10:24:59+00'),
('seed+sugar_daddy-003@genuinesugarmummies.com', 'William Nambooze', '/seed/sugar-dads/photo_13_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_13_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: serious matches, premium experiences. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, consistent, kind. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: serious matches, premium experiences. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, consistent, kind. Preferred age range: 21-35.', 45, 'London', 'United Kingdom', 'London', '+447663446859', '+447663446859', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'honest, consistent, kind, serious about meeting', '21-35', ARRAY['beach walks', 'photography', 'live music', 'fitness']::TEXT[], ARRAY['serious matches', 'premium experiences', 'discreet connection', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5837, 372, true, 'silver', true, '2026-06-25T12:03:59+00', '2026-06-25T12:03:59+00', '2026-06-22T09:24:59+00'),
('seed+sugar_daddy-004@genuinesugarmummies.com', 'Charles Nkurunziza', '/seed/sugar-dads/photo_14_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_14_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, clean communication, emotionally mature. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: honest, clean communication, emotionally mature. Preferred age range: 21-35.', 46, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254771389930', '+254771389930', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'honest, clean communication, emotionally mature, generous', '21-35', ARRAY['fitness', 'wine tasting', 'cooking', 'live music']::TEXT[], ARRAY['private dates', 'lifestyle support', 'premium experiences', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4909, 753, true, 'silver', true, '2026-06-25T11:56:59+00', '2026-06-25T11:56:59+00', '2026-06-21T08:24:59+00'),
('seed+sugar_daddy-005@genuinesugarmummies.com', 'George Okello', '/seed/sugar-dads/photo_15_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_15_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, respectful, clean communication. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, lifestyle support. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, respectful, clean communication. Preferred age range: 21-35.', 47, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254715157174', '+254715157174', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, respectful, clean communication, well groomed', '21-35', ARRAY['business events', 'fitness', 'travel', 'live music']::TEXT[], ARRAY['mentorship', 'lifestyle support', 'premium experiences', 'private dates']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2473, 578, true, 'silver', true, '2026-06-25T11:49:59+00', '2026-06-25T11:49:59+00', '2026-06-20T07:24:59+00'),
('seed+sugar_daddy-006@genuinesugarmummies.com', 'Henry Chebet', '/seed/sugar-dads/photo_16_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_16_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, respectful companionship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, serious about meeting, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, respectful companionship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, serious about meeting, consistent. Preferred age range: 21-35.', 48, 'Kisumu', 'Kenya', 'Kisumu', '+254716364742', '+254716364742', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, serious about meeting, consistent, generous', '21-35', ARRAY['spa days', 'cooking', 'dancing', 'art galleries']::TEXT[], ARRAY['private dates', 'respectful companionship', 'mentorship', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3993, 894, true, 'silver', true, '2026-06-25T11:42:59+00', '2026-06-25T11:42:59+00', '2026-06-19T06:24:59+00'),
('seed+sugar_daddy-007@genuinesugarmummies.com', 'Edward Johnson', '/seed/sugar-dads/photo_17_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_17_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, respectful companionship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, discreet, generous. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, respectful companionship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, discreet, generous. Preferred age range: 21-35.', 49, 'Mombasa', 'Kenya', 'Mombasa', '+254725685181', '+254725685181', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'serious about meeting, discreet, generous, well groomed', '21-35', ARRAY['cooking', 'travel', 'beach walks', 'art galleries']::TEXT[], ARRAY['private dates', 'respectful companionship', 'meaningful conversations', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3489, 794, true, 'silver', true, '2026-06-25T11:35:59+00', '2026-06-25T11:35:59+00', '2026-06-18T05:24:59+00'),
('seed+sugar_daddy-008@genuinesugarmummies.com', 'Michael Taylor', '/seed/sugar-dads/photo_18_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_18_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, kind, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, long-term arrangement. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, kind, serious about meeting. Preferred age range: 21-35.', 50, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254789163156', '+254789163156', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, kind, serious about meeting, well groomed', '21-35', ARRAY['business events', 'dancing', 'wine tasting', 'live music']::TEXT[], ARRAY['verified members', 'long-term arrangement', 'discreet connection', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6142, 636, true, 'silver', true, '2026-06-25T11:28:59+00', '2026-06-25T11:28:59+00', '2026-06-17T04:24:59+00'),
('seed+sugar_daddy-009@genuinesugarmummies.com', 'Daniel Wanjiku', '/seed/sugar-dads/photo_19_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_19_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, honest, generous. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: clean communication, honest, generous. Preferred age range: 21-35.', 51, 'Mombasa', 'Kenya', 'Mombasa', '+254710528361', '+254710528361', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'clean communication, honest, generous, well groomed', '21-35', ARRAY['dancing', 'live music', 'spa days', 'cooking']::TEXT[], ARRAY['mentorship', 'private dates', 'meaningful conversations', 'verified members']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5727, 473, true, 'silver', true, '2026-06-25T11:21:59+00', '2026-06-25T11:21:59+00', '2026-06-16T03:24:59+00'),
('seed+sugar_daddy-010@genuinesugarmummies.com', 'Richard Achieng', '/seed/sugar-dads/photo_20_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_20_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, discreet, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: emotionally mature, discreet, serious about meeting. Preferred age range: 21-35.', 52, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254724671015', '+254724671015', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'emotionally mature, discreet, serious about meeting, well groomed', '21-35', ARRAY['art galleries', 'fitness', 'fine dining', 'live music']::TEXT[], ARRAY['mentorship', 'serious matches', 'discreet connection', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5385, 242, true, 'silver', true, '2026-06-25T11:14:59+00', '2026-06-25T11:14:59+00', '2026-06-15T02:24:59+00'),
('seed+sugar_daddy-011@genuinesugarmummies.com', 'David Nabwire', '/seed/sugar-dads/photo_21_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_21_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, discreet, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: respectful companionship, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: serious about meeting, discreet, well groomed. Preferred age range: 21-35.', 53, 'Kampala', 'Uganda', 'Kampala', '+256769822131', '+256769822131', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'serious about meeting, discreet, well groomed, respectful', '21-35', ARRAY['wine tasting', 'fitness', 'weekend drives', 'travel']::TEXT[], ARRAY['respectful companionship', 'meaningful conversations', 'mentorship', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5812, 323, true, 'silver', true, '2026-06-25T11:07:59+00', '2026-06-25T11:07:59+00', '2026-06-14T01:24:59+00'),
('seed+sugar_daddy-012@genuinesugarmummies.com', 'Anthony Mugisha', '/seed/sugar-dads/photo_22_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_22_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: consistent, discreet, respectful. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: discreet connection, private dates. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: consistent, discreet, respectful. Preferred age range: 21-35.', 54, 'Arusha', 'Tanzania', 'Arusha', '+255739807053', '+255739807053', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'consistent, discreet, respectful, well groomed', '21-35', ARRAY['fitness', 'coffee dates', 'cooking', 'art galleries']::TEXT[], ARRAY['discreet connection', 'private dates', 'respectful companionship', 'lifestyle support']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 7129, 868, true, 'silver', true, '2026-06-25T11:00:59+00', '2026-06-25T11:00:59+00', '2026-06-13T00:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
