-- Seed profiles, batch 13 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_mummy-052@genuinesugarmummies.com', 'Jane Kariuki', '/seed/sugarmums/photo_56_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_56_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, honest, discreet. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: discreet connection, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, honest, discreet. Preferred age range: 21-34.', 48, 'Nairobi', 'Kenya', 'Nairobi', '+254799384815', '+254799384815', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'emotionally mature, honest, discreet, well groomed', '21-34', ARRAY['fitness', 'photography', 'travel', 'fashion']::TEXT[], ARRAY['discreet connection', 'mentorship', 'serious matches', 'private dates']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 974, 152, true, 'silver', true, '2026-06-25T06:20:59+00', '2026-06-25T06:20:59+00', '2026-05-04T08:24:59+00'),
('seed+sugar_mummy-053@genuinesugarmummies.com', 'Lucy Nambooze', '/seed/sugarmums/photo_57_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_57_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, well groomed, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: lifestyle support, respectful companionship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, well groomed, generous. Preferred age range: 21-34.', 49, 'Nakuru', 'Kenya', 'Nakuru', '+254727105433', '+254727105433', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, well groomed, generous, serious about meeting', '21-34', ARRAY['fine dining', 'spa days', 'coffee dates', 'live music']::TEXT[], ARRAY['lifestyle support', 'respectful companionship', 'private dates', 'serious matches']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 1373, 575, true, 'silver', true, '2026-06-25T06:13:59+00', '2026-06-25T06:13:59+00', '2026-05-03T07:24:59+00'),
('seed+sugar_mummy-054@genuinesugarmummies.com', 'Maryanne Nkurunziza', '/seed/sugarmums/photo_58_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_58_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, emotionally mature, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: premium experiences, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: generous, emotionally mature, respectful. Preferred age range: 21-34.', 50, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254763978292', '+254763978292', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'generous, emotionally mature, respectful, serious about meeting', '21-34', ARRAY['art galleries', 'spa days', 'live music', 'fitness']::TEXT[], ARRAY['premium experiences', 'mentorship', 'respectful companionship', 'long-term arrangement']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 377, 192, true, 'silver', true, '2026-06-25T06:06:59+00', '2026-06-25T06:06:59+00', '2026-05-02T06:24:59+00'),
('seed+sugar_mummy-055@genuinesugarmummies.com', 'Rebecca Okello', '/seed/sugarmums/photo_59_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_59_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, honest. Preferred age range: 21-34.', 51, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254774590755', '+254774590755', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, well groomed, honest, generous', '21-34', ARRAY['weekend drives', 'photography', 'fitness', 'fine dining']::TEXT[], ARRAY['respectful companionship', 'mentorship', 'private dates', 'meaningful conversations']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 1659, 291, true, 'silver', true, '2026-06-25T05:59:59+00', '2026-06-25T05:59:59+00', '2026-05-01T05:24:59+00'),
('seed+sugar_mummy-056@genuinesugarmummies.com', 'Susan Chebet', '/seed/sugarmums/photo_5_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_5_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, discreet, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: mentorship, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, discreet, emotionally mature. Preferred age range: 21-34.', 52, 'Thika', 'Kenya', 'Thika', '+254788997734', '+254788997734', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, discreet, emotionally mature, generous', '21-34', ARRAY['weekend drives', 'photography', 'art galleries', 'spa days']::TEXT[], ARRAY['mentorship', 'meaningful conversations', 'respectful companionship', 'premium experiences']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 7428, 666, true, 'silver', true, '2026-06-25T05:52:59+00', '2026-06-25T05:52:59+00', '2026-04-30T04:24:59+00'),
('seed+sugar_mummy-057@genuinesugarmummies.com', 'Teresa Johnson', '/seed/sugarmums/photo_61_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_61_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, emotionally mature, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, emotionally mature, respectful. Preferred age range: 21-34.', 53, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254759346961', '+254759346961', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, emotionally mature, respectful, clean communication', '21-34', ARRAY['coffee dates', 'fashion', 'travel', 'beach walks']::TEXT[], ARRAY['private dates', 'meaningful conversations', 'verified members', 'lifestyle support']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 6254, 469, true, 'silver', true, '2026-06-25T05:45:59+00', '2026-06-25T05:45:59+00', '2026-04-29T03:24:59+00'),
('seed+sugar_mummy-058@genuinesugarmummies.com', 'Victoria Taylor', '/seed/sugarmums/photo_63_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_63_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, respectful, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, mentorship. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: emotionally mature, respectful, generous. Preferred age range: 21-34.', 54, 'Entebbe', 'Uganda', 'Entebbe', '+256749267475', '+256749267475', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'emotionally mature, respectful, generous, serious about meeting', '21-34', ARRAY['fitness', 'business events', 'photography', 'cooking']::TEXT[], ARRAY['respectful companionship', 'mentorship', 'premium experiences', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5700, 427, true, 'silver', true, '2026-06-25T05:38:59+00', '2026-06-25T05:38:59+00', '2026-04-28T02:24:59+00'),
('seed+sugar_mummy-059@genuinesugarmummies.com', 'Agnes Wanjiku', '/seed/sugarmums/photo_64_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_64_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, clean communication, serious about meeting. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: well groomed, clean communication, serious about meeting. Preferred age range: 21-34.', 55, 'Mwanza', 'Tanzania', 'Mwanza', '+255787491774', '+255787491774', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'well groomed, clean communication, serious about meeting, consistent', '21-34', ARRAY['travel', 'spa days', 'fitness', 'fashion']::TEXT[], ARRAY['serious matches', 'lifestyle support', 'verified members', 'private dates']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 5830, 437, true, 'silver', true, '2026-06-25T05:31:59+00', '2026-06-25T05:31:59+00', '2026-04-27T01:24:59+00'),
('seed+sugar_mummy-060@genuinesugarmummies.com', 'Dorothy Achieng', '/seed/sugarmums/photo_66_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_66_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, generous, honest. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, verified members. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: consistent, generous, honest. Preferred age range: 21-34.', 56, 'Kigali', 'Rwanda', 'Kigali', '+250780630041', '+250780630041', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'consistent, generous, honest, respectful', '21-34', ARRAY['dancing', 'live music', 'spa days', 'business events']::TEXT[], ARRAY['private dates', 'verified members', 'discreet connection', 'mentorship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 4771, 219, true, 'silver', true, '2026-06-25T05:24:59+00', '2026-06-25T05:24:59+00', '2026-04-26T00:24:59+00'),
('seed+sugar_mummy-061@genuinesugarmummies.com', 'Elizabeth Nabwire', '/seed/sugarmums/photo_68_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_68_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, well groomed, respectful. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, lifestyle support. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: honest, well groomed, respectful. Preferred age range: 21-34.', 57, 'Kisumu', 'Kenya', 'Kisumu', '+254726638179', '+254726638179', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'honest, well groomed, respectful, emotionally mature', '21-34', ARRAY['fashion', 'cooking', 'coffee dates', 'art galleries']::TEXT[], ARRAY['private dates', 'lifestyle support', 'discreet connection', 'respectful companionship']::TEXT[], 'Elegant', 'silver', true, 'verified', true, false, false, 3822, 437, true, 'silver', true, '2026-06-25T05:17:59+00', '2026-06-25T05:17:59+00', '2026-04-24T23:24:59+00'),
('seed+sugar_mummy-062@genuinesugarmummies.com', 'Hellen Mugisha', '/seed/sugarmums/photo_69_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_69_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, emotionally mature, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: respectful companionship, long-term arrangement. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, emotionally mature, generous. Preferred age range: 21-34.', 58, 'Kilimani, Nairobi', 'Kenya', 'Kilimani, Nairobi', '+254764461264', '+254764461264', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, emotionally mature, generous, serious about meeting', '21-34', ARRAY['art galleries', 'spa days', 'dancing', 'fitness']::TEXT[], ARRAY['respectful companionship', 'long-term arrangement', 'mentorship', 'verified members']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 602, 729, true, 'silver', true, '2026-06-25T05:10:59+00', '2026-06-25T05:10:59+00', '2026-04-23T22:24:59+00'),
('seed+sugar_mummy-063@genuinesugarmummies.com', 'Judith Hassan', '/seed/sugarmums/photo_70_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_70_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, consistent, serious about meeting. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, meaningful conversations. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: kind, consistent, serious about meeting. Preferred age range: 21-34.', 38, 'Mombasa', 'Kenya', 'Mombasa', '+254758493892', '+254758493892', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'kind, consistent, serious about meeting, emotionally mature', '21-34', ARRAY['wine tasting', 'art galleries', 'fine dining', 'fitness']::TEXT[], ARRAY['long-term arrangement', 'meaningful conversations', 'verified members', 'serious matches']::TEXT[], 'Curvy', 'silver', true, 'verified', true, false, false, 5672, 94, true, 'silver', true, '2026-06-25T05:03:59+00', '2026-06-25T05:03:59+00', '2026-04-22T21:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
