-- Seed profiles, batch 8 of 16.
--
-- The original migration inserts all 181 in one 273 KB statement, which
-- the SQL Editor will not always accept. Split on top-level row boundaries
-- with quote and depth tracking, because the bios contain commas, brackets
-- and escaped quotes and a naive split produces SQL that does not parse.
--
-- ON CONFLICT is preserved on every batch, so re-running is safe.

INSERT INTO public.users (email, display_name, avatar_url, photos, bio, description, age, location, country, city, phone, phone_number, profile_label, member_category, looking_for, intent_summary, wants, needed_qualities, age_range_preference, hobbies, interests, body_type, subscription_tier, verified, verification_status, show_in_public, is_banned, is_suspended, total_profile_views, followers_count, admin_approved, phone_reveal_plan, is_seed_profile, last_seen_at, last_seen, created_at) VALUES

('seed+sugar_daddy-037@genuinesugarmummies.com', 'Ronald Mugisha', '/seed/sugar-dads/photo_57_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_57_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, clean communication, serious about meeting. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, clean communication, serious about meeting. Preferred age range: 21-35.', 55, 'Nyali, Mombasa', 'Kenya', 'Nyali, Mombasa', '+254740717457', '+254740717457', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, clean communication, serious about meeting, honest', '21-35', ARRAY['fine dining', 'fitness', 'weekend drives', 'dancing']::TEXT[], ARRAY['verified members', 'mentorship', 'meaningful conversations', 'respectful companionship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 209, 343, true, 'silver', true, '2026-06-25T08:05:59+00', '2026-06-25T08:05:59+00', '2026-05-18T23:24:59+00'),
('seed+sugar_daddy-038@genuinesugarmummies.com', 'Raymond Hassan', '/seed/sugar-dads/photo_58_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_58_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, well groomed, honest. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: long-term arrangement, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, well groomed, honest. Preferred age range: 21-35.', 56, 'Kisumu', 'Kenya', 'Kisumu', '+254756638169', '+254756638169', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'generous, well groomed, honest, kind', '21-35', ARRAY['fitness', 'fine dining', 'weekend drives', 'photography']::TEXT[], ARRAY['long-term arrangement', 'verified members', 'private dates', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 973, 619, true, 'silver', true, '2026-06-25T07:58:59+00', '2026-06-25T07:58:59+00', '2026-05-17T22:24:59+00'),
('seed+sugar_daddy-039@genuinesugarmummies.com', 'Walter Wafula', '/seed/sugar-dads/photo_59_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_59_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, serious about meeting, well groomed. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, mentorship. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: respectful, serious about meeting, well groomed. Preferred age range: 21-35.', 57, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254761546980', '+254761546980', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'respectful, serious about meeting, well groomed, kind', '21-35', ARRAY['coffee dates', 'live music', 'business events', 'fine dining']::TEXT[], ARRAY['verified members', 'mentorship', 'discreet connection', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 964, 714, true, 'silver', true, '2026-06-25T07:51:59+00', '2026-06-25T07:51:59+00', '2026-05-16T21:24:59+00'),
('seed+sugar_daddy-040@genuinesugarmummies.com', 'Graham Smith', '/seed/sugar-dads/photo_5_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_5_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, honest, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: premium experiences, meaningful conversations. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, honest, consistent. Preferred age range: 21-35.', 58, 'Westlands, Nairobi', 'Kenya', 'Westlands, Nairobi', '+254786656329', '+254786656329', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, honest, consistent, emotionally mature', '21-35', ARRAY['photography', 'art galleries', 'travel', 'dancing']::TEXT[], ARRAY['premium experiences', 'meaningful conversations', 'private dates', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 3796, 313, true, 'silver', true, '2026-06-25T07:44:59+00', '2026-06-25T07:44:59+00', '2026-05-15T20:24:59+00'),
('seed+sugar_daddy-041@genuinesugarmummies.com', 'Arthur Brown', '/seed/sugar-dads/photo_60_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugar-dads/photo_60_2026-06-24_14-00-45.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, emotionally mature, kind. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, emotionally mature, kind. Preferred age range: 21-35.', 59, 'Jinja', 'Uganda', 'Jinja', '+256768518098', '+256768518098', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, emotionally mature, kind, clean communication', '21-35', ARRAY['business events', 'beach walks', 'travel', 'photography']::TEXT[], ARRAY['private dates', 'verified members', 'lifestyle support', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6056, 437, true, 'silver', true, '2026-06-25T07:37:59+00', '2026-06-25T07:37:59+00', '2026-05-14T19:24:59+00'),
('seed+sugar_daddy-042@genuinesugarmummies.com', 'Leonard Otieno', '/seed/sugar-dads/photo_6_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_6_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, premium experiences. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, generous, honest. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: mentorship, premium experiences. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, generous, honest. Preferred age range: 21-35.', 60, 'Dar es Salaam', 'Tanzania', 'Dar es Salaam', '+255720197758', '+255720197758', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, generous, honest, kind', '21-35', ARRAY['fashion', 'beach walks', 'wine tasting', 'spa days']::TEXT[], ARRAY['mentorship', 'premium experiences', 'meaningful conversations', 'verified members']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 871, 454, true, 'silver', true, '2026-06-25T07:30:59+00', '2026-06-25T07:30:59+00', '2026-05-13T18:24:59+00'),
('seed+sugar_daddy-043@genuinesugarmummies.com', 'Bruce Njeri', '/seed/sugar-dads/photo_7_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_7_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: serious matches, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, kind, consistent. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: serious matches, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: generous, kind, consistent. Preferred age range: 21-35.', 61, 'Gisenyi', 'Rwanda', 'Gisenyi', '+250795886730', '+250795886730', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'generous, kind, consistent, honest', '21-35', ARRAY['dancing', 'weekend drives', 'coffee dates', 'fine dining']::TEXT[], ARRAY['serious matches', 'verified members', 'premium experiences', 'discreet connection']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 7191, 445, true, 'silver', true, '2026-06-25T07:23:59+00', '2026-06-25T07:23:59+00', '2026-05-12T17:24:59+00'),
('seed+sugar_daddy-044@genuinesugarmummies.com', 'Harold Mutiso', '/seed/sugar-dads/photo_8_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_8_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, emotionally mature, generous. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: private dates, verified members. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: well groomed, emotionally mature, generous. Preferred age range: 21-35.', 62, 'Nairobi', 'Kenya', 'Nairobi', '+254781485415', '+254781485415', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'well groomed, emotionally mature, generous, clean communication', '21-35', ARRAY['fitness', 'business events', 'wine tasting', 'fashion']::TEXT[], ARRAY['private dates', 'verified members', 'lifestyle support', 'serious matches']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 6327, 129, true, 'silver', true, '2026-06-25T07:16:59+00', '2026-06-25T07:16:59+00', '2026-05-11T16:24:59+00'),
('seed+sugar_daddy-045@genuinesugarmummies.com', 'Vincent Kato', '/seed/sugar-dads/photo_9_2026-06-25_14-22-09.jpg', ARRAY['/seed/sugar-dads/photo_9_2026-06-25_14-22-09.jpg']::TEXT[], 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, respectful, clean communication. Preferred age range: 21-35.', 'Established sugar daddy who values discretion, good conversation, and dependable connection. Interests: verified members, serious matches. Wants: A classy adult mistress who values privacy, honesty, and relaxed premium companionship. Needed qualities: discreet, respectful, clean communication. Preferred age range: 21-35.', 63, 'Eldoret', 'Kenya', 'Eldoret', '+254799899444', '+254799899444', 'sugar_daddy', 'sugar_daddy', 'Mistress', 'I am a sugar daddy looking for Mistress.', 'A classy adult mistress who values privacy, honesty, and relaxed premium companionship.', 'discreet, respectful, clean communication, well groomed', '21-35', ARRAY['business events', 'live music', 'dancing', 'beach walks']::TEXT[], ARRAY['verified members', 'serious matches', 'respectful companionship', 'mentorship']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 2863, 328, true, 'silver', true, '2026-06-25T07:09:59+00', '2026-06-25T07:09:59+00', '2026-05-10T15:24:59+00'),
('seed+sugar_mummy-001@genuinesugarmummies.com', 'Margaret Kamau', '/seed/sugarmums/photo_100_2026-06-25_14-21-42.jpg', ARRAY['/seed/sugarmums/photo_100_2026-06-25_14-21-42.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, generous, emotionally mature. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: long-term arrangement, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: respectful, generous, emotionally mature. Preferred age range: 21-34.', 39, 'Nairobi', 'Kenya', 'Nairobi', '+254763575682', '+254763575682', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'respectful, generous, emotionally mature, well groomed', '21-34', ARRAY['weekend drives', 'cooking', 'wine tasting', 'business events']::TEXT[], ARRAY['long-term arrangement', 'private dates', 'meaningful conversations', 'premium experiences']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 1369, 361, true, 'silver', true, '2026-06-25T12:17:59+00', '2026-06-25T12:17:59+00', '2026-06-24T11:24:59+00'),
('seed+sugar_mummy-002@genuinesugarmummies.com', 'Catherine Kariuki', '/seed/sugarmums/photo_10_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_10_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, respectful, generous. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: serious matches, private dates. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: clean communication, respectful, generous. Preferred age range: 21-34.', 40, 'Eldoret', 'Kenya', 'Eldoret', '+254766794093', '+254766794093', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'clean communication, respectful, generous, serious about meeting', '21-34', ARRAY['photography', 'fashion', 'dancing', 'business events']::TEXT[], ARRAY['serious matches', 'private dates', 'respectful companionship', 'verified members']::TEXT[], 'Average', 'silver', true, 'verified', true, false, false, 4058, 446, true, 'silver', true, '2026-06-25T12:10:59+00', '2026-06-25T12:10:59+00', '2026-06-23T10:24:59+00'),
('seed+sugar_mummy-003@genuinesugarmummies.com', 'Janet Nambooze', '/seed/sugarmums/photo_11_2026-06-24_14-00-45.jpg', ARRAY['/seed/sugarmums/photo_11_2026-06-24_14-00-45.jpg']::TEXT[], 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, serious about meeting. Preferred age range: 21-34.', 'Genuine sugar mummy seeking a warm, discreet connection with an attentive younger gentleman. Interests: private dates, premium experiences. Wants: A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious. Needed qualities: discreet, well groomed, serious about meeting. Preferred age range: 21-34.', 41, 'Karen, Nairobi', 'Kenya', 'Karen, Nairobi', '+254738514463', '+254738514463', 'sugar_mummy', 'sugar_mummy', 'Sugar Guy / Toyboy', 'I am a sugar mummy looking for Sugar Guy / Toyboy.', 'A confident sugar guy or toyboy who is respectful, attentive, energetic, and serious.', 'discreet, well groomed, serious about meeting, respectful', '21-34', ARRAY['fitness', 'live music', 'dancing', 'coffee dates']::TEXT[], ARRAY['private dates', 'premium experiences', 'long-term arrangement', 'respectful companionship']::TEXT[], 'Fit', 'silver', true, 'verified', true, false, false, 528, 625, true, 'silver', true, '2026-06-25T12:03:59+00', '2026-06-25T12:03:59+00', '2026-06-22T09:24:59+00')

ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    photos = EXCLUDED.photos,
    bio = EXCLUDED.bio,
    description = EXCLUDED.description,
    age = EXCLUDED.age,
    location = EXCLUDED.location,
    country = EXCLUDED.country,
    city = EXCLUDED.city,
    phone = EXCLUDED.phone,
    phone_number = EXCLUDED.phone_number,
    profile_label = EXCLUDED.profile_label,
    member_category = EXCLUDED.member_category,
    looking_for = EXCLUDED.looking_for,
    intent_summary = EXCLUDED.intent_summary,
    wants = EXCLUDED.wants,
    needed_qualities = EXCLUDED.needed_qualities,
    age_range_preference = EXCLUDED.age_range_preference,
    hobbies = EXCLUDED.hobbies,
    interests = EXCLUDED.interests,
    body_type = EXCLUDED.body_type,
    subscription_tier = EXCLUDED.subscription_tier,
    verified = EXCLUDED.verified,
    verification_status = EXCLUDED.verification_status,
    show_in_public = EXCLUDED.show_in_public,
    is_banned = EXCLUDED.is_banned,
    is_suspended = EXCLUDED.is_suspended,
    total_profile_views = GREATEST(public.users.total_profile_views, EXCLUDED.total_profile_views),
    followers_count = GREATEST(public.users.followers_count, EXCLUDED.followers_count),
    admin_approved = EXCLUDED.admin_approved,
    phone_reveal_plan = EXCLUDED.phone_reveal_plan,
    is_seed_profile = EXCLUDED.is_seed_profile,
    last_seen_at = EXCLUDED.last_seen_at,
    last_seen = EXCLUDED.last_seen;
